package com.microwill.project.DG.entity;

// Generated 2014-5-6 23:15:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AincGatewayNetcfgMr generated by hbm2java
 */
@Entity
@Table(name = "ainc_gateway_netcfg_mr", catalog = "netctrl")
public class AincGatewayNetcfgMr implements java.io.Serializable {

	private String ngnmId;
	private String ngnmGatewayIp;
	private String ngnmMac;
	private String ngnmConnectMode;
	private String ngnmTransportProtocol;
	private String ngnmTransportMode;
	private String ngnmGrade;
	private String ngnmCfgPar1;
	private String ngnmCfgPar2;
	private String ngnmCfgPar3;
	private String ngnmDaPar1;
	private String ngnmDaPar2;
	private String ngnmDaPar3;
	private String ngnmCtrlPar1;
	private String ngnmCtrlPar2;
	private String ngnmCtrlPar3;

	public AincGatewayNetcfgMr() {
	}

	public AincGatewayNetcfgMr(String ngnmId, String ngnmConnectMode,
			String ngnmTransportProtocol) {
		this.ngnmId = ngnmId;
		this.ngnmConnectMode = ngnmConnectMode;
		this.ngnmTransportProtocol = ngnmTransportProtocol;
	}

	public AincGatewayNetcfgMr(String ngnmId, String ngnmGatewayIp,
			String ngnmMac, String ngnmConnectMode,
			String ngnmTransportProtocol, String ngnmTransportMode,
			String ngnmGrade, String ngnmCfgPar1, String ngnmCfgPar2,
			String ngnmCfgPar3, String ngnmDaPar1, String ngnmDaPar2,
			String ngnmDaPar3, String ngnmCtrlPar1, String ngnmCtrlPar2,
			String ngnmCtrlPar3) {
		this.ngnmId = ngnmId;
		this.ngnmGatewayIp = ngnmGatewayIp;
		this.ngnmMac = ngnmMac;
		this.ngnmConnectMode = ngnmConnectMode;
		this.ngnmTransportProtocol = ngnmTransportProtocol;
		this.ngnmTransportMode = ngnmTransportMode;
		this.ngnmGrade = ngnmGrade;
		this.ngnmCfgPar1 = ngnmCfgPar1;
		this.ngnmCfgPar2 = ngnmCfgPar2;
		this.ngnmCfgPar3 = ngnmCfgPar3;
		this.ngnmDaPar1 = ngnmDaPar1;
		this.ngnmDaPar2 = ngnmDaPar2;
		this.ngnmDaPar3 = ngnmDaPar3;
		this.ngnmCtrlPar1 = ngnmCtrlPar1;
		this.ngnmCtrlPar2 = ngnmCtrlPar2;
		this.ngnmCtrlPar3 = ngnmCtrlPar3;
	}

	@Id
	@Column(name = "ngnm_id", unique = true, nullable = false, length = 12)
	public String getNgnmId() {
		return this.ngnmId;
	}

	public void setNgnmId(String ngnmId) {
		this.ngnmId = ngnmId;
	}

	@Column(name = "ngnm_gateway_ip", length = 15)
	public String getNgnmGatewayIp() {
		return this.ngnmGatewayIp;
	}

	public void setNgnmGatewayIp(String ngnmGatewayIp) {
		this.ngnmGatewayIp = ngnmGatewayIp;
	}

	@Column(name = "ngnm_MAC", length = 20)
	public String getNgnmMac() {
		return this.ngnmMac;
	}

	public void setNgnmMac(String ngnmMac) {
		this.ngnmMac = ngnmMac;
	}

	@Column(name = "ngnm_connect_mode", nullable = false, length = 10)
	public String getNgnmConnectMode() {
		return this.ngnmConnectMode;
	}

	public void setNgnmConnectMode(String ngnmConnectMode) {
		this.ngnmConnectMode = ngnmConnectMode;
	}

	@Column(name = "ngnm_transport_protocol", nullable = false, length = 12)
	public String getNgnmTransportProtocol() {
		return this.ngnmTransportProtocol;
	}

	public void setNgnmTransportProtocol(String ngnmTransportProtocol) {
		this.ngnmTransportProtocol = ngnmTransportProtocol;
	}

	@Column(name = "ngnm_transport_mode", length = 2)
	public String getNgnmTransportMode() {
		return this.ngnmTransportMode;
	}

	public void setNgnmTransportMode(String ngnmTransportMode) {
		this.ngnmTransportMode = ngnmTransportMode;
	}

	@Column(name = "ngnm_grade", length = 10)
	public String getNgnmGrade() {
		return this.ngnmGrade;
	}

	public void setNgnmGrade(String ngnmGrade) {
		this.ngnmGrade = ngnmGrade;
	}

	@Column(name = "ngnm_cfg_par1", length = 10)
	public String getNgnmCfgPar1() {
		return this.ngnmCfgPar1;
	}

	public void setNgnmCfgPar1(String ngnmCfgPar1) {
		this.ngnmCfgPar1 = ngnmCfgPar1;
	}

	@Column(name = "ngnm_cfg_par2", length = 10)
	public String getNgnmCfgPar2() {
		return this.ngnmCfgPar2;
	}

	public void setNgnmCfgPar2(String ngnmCfgPar2) {
		this.ngnmCfgPar2 = ngnmCfgPar2;
	}

	@Column(name = "ngnm_cfg_par3", length = 10)
	public String getNgnmCfgPar3() {
		return this.ngnmCfgPar3;
	}

	public void setNgnmCfgPar3(String ngnmCfgPar3) {
		this.ngnmCfgPar3 = ngnmCfgPar3;
	}

	@Column(name = "ngnm_da_par1", length = 10)
	public String getNgnmDaPar1() {
		return this.ngnmDaPar1;
	}

	public void setNgnmDaPar1(String ngnmDaPar1) {
		this.ngnmDaPar1 = ngnmDaPar1;
	}

	@Column(name = "ngnm_da_par2", length = 10)
	public String getNgnmDaPar2() {
		return this.ngnmDaPar2;
	}

	public void setNgnmDaPar2(String ngnmDaPar2) {
		this.ngnmDaPar2 = ngnmDaPar2;
	}

	@Column(name = "ngnm_da_par3", length = 10)
	public String getNgnmDaPar3() {
		return this.ngnmDaPar3;
	}

	public void setNgnmDaPar3(String ngnmDaPar3) {
		this.ngnmDaPar3 = ngnmDaPar3;
	}

	@Column(name = "ngnm_ctrl_par1", length = 10)
	public String getNgnmCtrlPar1() {
		return this.ngnmCtrlPar1;
	}

	public void setNgnmCtrlPar1(String ngnmCtrlPar1) {
		this.ngnmCtrlPar1 = ngnmCtrlPar1;
	}

	@Column(name = "ngnm_ctrl_par2", length = 10)
	public String getNgnmCtrlPar2() {
		return this.ngnmCtrlPar2;
	}

	public void setNgnmCtrlPar2(String ngnmCtrlPar2) {
		this.ngnmCtrlPar2 = ngnmCtrlPar2;
	}

	@Column(name = "ngnm_ctrl_par3", length = 10)
	public String getNgnmCtrlPar3() {
		return this.ngnmCtrlPar3;
	}

	public void setNgnmCtrlPar3(String ngnmCtrlPar3) {
		this.ngnmCtrlPar3 = ngnmCtrlPar3;
	}

}
