package com.microwill.project.DG.entity;

// Generated 2014-5-6 23:15:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AincGatewayMr generated by hbm2java
 */
@Entity
@Table(name = "ainc_gateway_mr", catalog = "netctrl")
public class AincGatewayMr implements java.io.Serializable {

	private String ngmId;
	private String ngmName;
	private String ngmSnNo;
	private String ngmOrg;
	private String ngmStatus;
	private String ngmPar1;
	private String ngmPar2;
	private String ngmPar3;
	private String ngmPar4;
	private String ngmPar5;
	private Float ngmPar6;
	private Float ngmPar7;
	private Float ngmPar8;
	private Float ngmPar9;
	private Float ngmPar10;
	private String ngmRemark;

	public AincGatewayMr() {
	}

	public AincGatewayMr(String ngmId, String ngmName, String ngmSnNo,
			String ngmStatus) {
		this.ngmId = ngmId;
		this.ngmName = ngmName;
		this.ngmSnNo = ngmSnNo;
		this.ngmStatus = ngmStatus;
	}

	public AincGatewayMr(String ngmId, String ngmName, String ngmSnNo,
			String ngmOrg, String ngmStatus, String ngmPar1, String ngmPar2,
			String ngmPar3, String ngmPar4, String ngmPar5, Float ngmPar6,
			Float ngmPar7, Float ngmPar8, Float ngmPar9, Float ngmPar10,
			String ngmRemark) {
		this.ngmId = ngmId;
		this.ngmName = ngmName;
		this.ngmSnNo = ngmSnNo;
		this.ngmOrg = ngmOrg;
		this.ngmStatus = ngmStatus;
		this.ngmPar1 = ngmPar1;
		this.ngmPar2 = ngmPar2;
		this.ngmPar3 = ngmPar3;
		this.ngmPar4 = ngmPar4;
		this.ngmPar5 = ngmPar5;
		this.ngmPar6 = ngmPar6;
		this.ngmPar7 = ngmPar7;
		this.ngmPar8 = ngmPar8;
		this.ngmPar9 = ngmPar9;
		this.ngmPar10 = ngmPar10;
		this.ngmRemark = ngmRemark;
	}

	@Id
	@Column(name = "ngm_id", unique = true, nullable = false, length = 12)
	public String getNgmId() {
		return this.ngmId;
	}

	public void setNgmId(String ngmId) {
		this.ngmId = ngmId;
	}

	@Column(name = "ngm_name", nullable = false, length = 100)
	public String getNgmName() {
		return this.ngmName;
	}

	public void setNgmName(String ngmName) {
		this.ngmName = ngmName;
	}

	@Column(name = "ngm_sn_no", nullable = false, length = 16)
	public String getNgmSnNo() {
		return this.ngmSnNo;
	}

	public void setNgmSnNo(String ngmSnNo) {
		this.ngmSnNo = ngmSnNo;
	}

	@Column(name = "ngm_org", length = 100)
	public String getNgmOrg() {
		return this.ngmOrg;
	}

	public void setNgmOrg(String ngmOrg) {
		this.ngmOrg = ngmOrg;
	}

	@Column(name = "ngm_status", nullable = false, length = 1)
	public String getNgmStatus() {
		return this.ngmStatus;
	}

	public void setNgmStatus(String ngmStatus) {
		this.ngmStatus = ngmStatus;
	}

	@Column(name = "ngm_par1", length = 100)
	public String getNgmPar1() {
		return this.ngmPar1;
	}

	public void setNgmPar1(String ngmPar1) {
		this.ngmPar1 = ngmPar1;
	}

	@Column(name = "ngm_par2", length = 100)
	public String getNgmPar2() {
		return this.ngmPar2;
	}

	public void setNgmPar2(String ngmPar2) {
		this.ngmPar2 = ngmPar2;
	}

	@Column(name = "ngm_par3", length = 10)
	public String getNgmPar3() {
		return this.ngmPar3;
	}

	public void setNgmPar3(String ngmPar3) {
		this.ngmPar3 = ngmPar3;
	}

	@Column(name = "ngm_par4", length = 10)
	public String getNgmPar4() {
		return this.ngmPar4;
	}

	public void setNgmPar4(String ngmPar4) {
		this.ngmPar4 = ngmPar4;
	}

	@Column(name = "ngm_par5", length = 100)
	public String getNgmPar5() {
		return this.ngmPar5;
	}

	public void setNgmPar5(String ngmPar5) {
		this.ngmPar5 = ngmPar5;
	}

	@Column(name = "ngm_par6", precision = 8, scale = 0)
	public Float getNgmPar6() {
		return this.ngmPar6;
	}

	public void setNgmPar6(Float ngmPar6) {
		this.ngmPar6 = ngmPar6;
	}

	@Column(name = "ngm_par7", precision = 8, scale = 0)
	public Float getNgmPar7() {
		return this.ngmPar7;
	}

	public void setNgmPar7(Float ngmPar7) {
		this.ngmPar7 = ngmPar7;
	}

	@Column(name = "ngm_par8", precision = 8, scale = 0)
	public Float getNgmPar8() {
		return this.ngmPar8;
	}

	public void setNgmPar8(Float ngmPar8) {
		this.ngmPar8 = ngmPar8;
	}

	@Column(name = "ngm_par9", precision = 8, scale = 0)
	public Float getNgmPar9() {
		return this.ngmPar9;
	}

	public void setNgmPar9(Float ngmPar9) {
		this.ngmPar9 = ngmPar9;
	}

	@Column(name = "ngm_par10", precision = 8, scale = 0)
	public Float getNgmPar10() {
		return this.ngmPar10;
	}

	public void setNgmPar10(Float ngmPar10) {
		this.ngmPar10 = ngmPar10;
	}

	@Column(name = "ngm_remark", length = 100)
	public String getNgmRemark() {
		return this.ngmRemark;
	}

	public void setNgmRemark(String ngmRemark) {
		this.ngmRemark = ngmRemark;
	}

}
