package com.microwill.project.DG.entity;

// Generated 2014-5-6 23:15:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AincUserMr generated by hbm2java
 */
@Entity
@Table(name = "ainc_user_mr", catalog = "netctrl")
public class AincUserMr implements java.io.Serializable {

	private long numUserId;
	private String numLoginName;
	private String numPassword;
	private String numName;
	private String numMoblieNo;
	private String numCountry;
	private String numCity;
	private String numAddress;
	private String numEmail;
	private String numServiceId;
	private String numAccount;
	private Date numCreateDate;
	private Date numLastDate;
	private String numRemark;

	public AincUserMr() {
	}

	public AincUserMr(long numUserId, String numLoginName, String numPassword,
			Date numCreateDate, Date numLastDate) {
		this.numUserId = numUserId;
		this.numLoginName = numLoginName;
		this.numPassword = numPassword;
		this.numCreateDate = numCreateDate;
		this.numLastDate = numLastDate;
	}

	public AincUserMr(long numUserId, String numLoginName, String numPassword,
			String numName, String numMoblieNo, String numCountry,
			String numCity, String numAddress, String numEmail,
			String numServiceId, String numAccount, Date numCreateDate,
			Date numLastDate, String numRemark) {
		this.numUserId = numUserId;
		this.numLoginName = numLoginName;
		this.numPassword = numPassword;
		this.numName = numName;
		this.numMoblieNo = numMoblieNo;
		this.numCountry = numCountry;
		this.numCity = numCity;
		this.numAddress = numAddress;
		this.numEmail = numEmail;
		this.numServiceId = numServiceId;
		this.numAccount = numAccount;
		this.numCreateDate = numCreateDate;
		this.numLastDate = numLastDate;
		this.numRemark = numRemark;
	}

	@Id
	@Column(name = "num_user_id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getNumUserId() {
		return this.numUserId;
	}

	public void setNumUserId(long numUserId) {
		this.numUserId = numUserId;
	}

	@Column(name = "num_login_name", nullable = false, length = 20)
	public String getNumLoginName() {
		return this.numLoginName;
	}

	public void setNumLoginName(String numLoginName) {
		this.numLoginName = numLoginName;
	}

	@Column(name = "num_password", nullable = false, length = 20)
	public String getNumPassword() {
		return this.numPassword;
	}

	public void setNumPassword(String numPassword) {
		this.numPassword = numPassword;
	}

	@Column(name = "num_name", length = 20)
	public String getNumName() {
		return this.numName;
	}

	public void setNumName(String numName) {
		this.numName = numName;
	}

	@Column(name = "num_moblie_no", length = 15)
	public String getNumMoblieNo() {
		return this.numMoblieNo;
	}

	public void setNumMoblieNo(String numMoblieNo) {
		this.numMoblieNo = numMoblieNo;
	}

	@Column(name = "num_country", length = 100)
	public String getNumCountry() {
		return this.numCountry;
	}

	public void setNumCountry(String numCountry) {
		this.numCountry = numCountry;
	}

	@Column(name = "num_city", length = 100)
	public String getNumCity() {
		return this.numCity;
	}

	public void setNumCity(String numCity) {
		this.numCity = numCity;
	}

	@Column(name = "num_address", length = 100)
	public String getNumAddress() {
		return this.numAddress;
	}

	public void setNumAddress(String numAddress) {
		this.numAddress = numAddress;
	}

	@Column(name = "num_email", length = 100)
	public String getNumEmail() {
		return this.numEmail;
	}

	public void setNumEmail(String numEmail) {
		this.numEmail = numEmail;
	}

	@Column(name = "num_service_id", length = 12)
	public String getNumServiceId() {
		return this.numServiceId;
	}

	public void setNumServiceId(String numServiceId) {
		this.numServiceId = numServiceId;
	}

	@Column(name = "num_account", length = 30)
	public String getNumAccount() {
		return this.numAccount;
	}

	public void setNumAccount(String numAccount) {
		this.numAccount = numAccount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "num_create_date", nullable = false, length = 19)
	public Date getNumCreateDate() {
		return this.numCreateDate;
	}

	public void setNumCreateDate(Date numCreateDate) {
		this.numCreateDate = numCreateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "num_last_date", nullable = false, length = 19)
	public Date getNumLastDate() {
		return this.numLastDate;
	}

	public void setNumLastDate(Date numLastDate) {
		this.numLastDate = numLastDate;
	}

	@Column(name = "num_remark", length = 100)
	public String getNumRemark() {
		return this.numRemark;
	}

	public void setNumRemark(String numRemark) {
		this.numRemark = numRemark;
	}

}
