package com.microwill.project.BGM.entity;

// Generated 2013-12-14 14:53:46 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TDict generated by hbm2java
 */
@Entity
@Table(name = "t_dict", catalog = "BGM")
public class TDict implements java.io.Serializable {

	private String dictId;
	private String dictCode;
	private String dictText;
	private String parentId;
	private String dictType;

	public TDict() {
	}

	public TDict(String dictId) {
		this.dictId = dictId;
	}

	public TDict(String dictId, String dictCode, String dictText,
			String parentId, String dictType) {
		this.dictId = dictId;
		this.dictCode = dictCode;
		this.dictText = dictText;
		this.parentId = parentId;
		this.dictType = dictType;
	}

	@Id
	@Column(name = "dict_id", unique = true, nullable = false, length = 32)
	public String getDictId() {
		return this.dictId;
	}

	public void setDictId(String dictId) {
		this.dictId = dictId;
	}

	@Column(name = "dict_code", length = 10)
	public String getDictCode() {
		return this.dictCode;
	}

	public void setDictCode(String dictCode) {
		this.dictCode = dictCode;
	}

	@Column(name = "dict_text", length = 30)
	public String getDictText() {
		return this.dictText;
	}

	public void setDictText(String dictText) {
		this.dictText = dictText;
	}

	@Column(name = "parent_id", length = 32)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "dict_type", length = 10)
	public String getDictType() {
		return this.dictType;
	}

	public void setDictType(String dictType) {
		this.dictType = dictType;
	}

}
