package com.microwill.project.BGM.entity;

// Generated 2013-12-14 14:53:46 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TPlan generated by hbm2java
 */
@Entity
@Table(name = "t_plan", catalog = "BGM")
public class TPlan implements java.io.Serializable {

	private String planId;
	private String patientId;
	private String userId;
	private String beginTime;
	private String endTime;
	private String memo;
	private Integer dectectTime;

	public TPlan() {
	}

	public TPlan(String planId) {
		this.planId = planId;
	}

	public TPlan(String planId, String patientId, String userId,
			String beginTime, String endTime, String memo, Integer dectectTime) {
		this.planId = planId;
		this.patientId = patientId;
		this.userId = userId;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.memo = memo;
		this.dectectTime = dectectTime;
	}

	@Id
	@Column(name = "plan_id", unique = true, nullable = false, length = 32)
	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	@Column(name = "patient_id", length = 32)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "begin_time", length = 16)
	public String getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	@Column(name = "end_time", length = 16)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "memo", length = 150)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "dectect_time")
	public Integer getDectectTime() {
		return this.dectectTime;
	}

	public void setDectectTime(Integer dectectTime) {
		this.dectectTime = dectectTime;
	}

}
