package com.microwill.project.BGM.entity;

// Generated 2013-12-14 14:53:46 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTerminal generated by hbm2java
 */
@Entity
@Table(name = "t_terminal", catalog = "BGM")
public class TTerminal implements java.io.Serializable {

	private String machId;
	private Integer isRegister;

	public TTerminal() {
	}

	public TTerminal(String machId) {
		this.machId = machId;
	}

	public TTerminal(String machId, Integer isRegister) {
		this.machId = machId;
		this.isRegister = isRegister;
	}

	@Id
	@Column(name = "mach_id", unique = true, nullable = false, length = 32)
	public String getMachId() {
		return this.machId;
	}

	public void setMachId(String machId) {
		this.machId = machId;
	}

	@Column(name = "is_register")
	public Integer getIsRegister() {
		return this.isRegister;
	}

	public void setIsRegister(Integer isRegister) {
		this.isRegister = isRegister;
	}

}
