/*
dhtmlxTouch v.0.4 alpha 101210 
Copyright DHTMLX LTD. http://www.dhtmlx.com
You allowed to use this component or parts of it under GPL terms
To use it on other terms please contact us at sales@dhtmlx.com
*/
window.dhx||(dhx={});dhx.version="3.0";dhx.codebase="./";dhx.name="Core";dhx.copy=function(a){var b=dhx.copy.mc;b.prototype=a;return new b};dhx.copy.mc=function(){};dhx.extend=function(a,b,c){for(var d in b)if(!a[d]||c)a[d]=b[d];b.defaults&&dhx.extend(a.defaults,b.defaults);b.h&&b.h.call(a);return a};dhx.single=function(a){var b=null,c=function(){b||(b=new a({}));b.Bb&&b.Bb.apply(b,arguments);return b};return c};
dhx.proto=function(){for(var a=arguments,b=a[0],c=[],d=a.length-1;d>0;d--){if(typeof a[d]=="function")a[d]=a[d].prototype;a[d].h&&c.push(a[d].h);if(a[d].defaults){var e=a[d].defaults;if(!b.defaults)b.defaults={};for(var f in e)b.defaults[f]||(b.defaults[f]=e[f])}for(var g in a[d])b[g]||(b[g]=a[d][g])}a[0].h&&c.push(a[0].h);b.h=function(){for(var i=0;i<c.length;i++)c[i].apply(this,arguments)};var h=function(i){this.G=[];this.h(i);this.ma&&this.ma(i,this.defaults);for(i=0;i<this.G.length;i++)this.G[i].call(this)};
h.prototype=b;b=a=null;return h};dhx.bind=function(a,b){return function(){return a.apply(b,arguments)}};dhx.require=function(a){if(!dhx.vb[a]){dhx.exec(dhx.ajax().sync().get(dhx.codebase+a).responseText);dhx.vb[a]=true}};dhx.vb={};dhx.exec=function(a){window.execScript?window.execScript(a):window.eval(a)};dhx.methodPush=function(a,b){return function(){var c=false;return c=a[b].apply(a,arguments)}};dhx.isNotDefined=function(a){return typeof a=="undefined"};
dhx.delay=function(a,b,c,d){return setTimeout(function(){var e=a.apply(b,c);a=b=c=null;return e},d||1)};dhx.uid=function(){if(!this.$a)this.$a=(new Date).valueOf();this.$a++;return this.$a};dhx.toNode=function(a){if(typeof a=="string")return document.getElementById(a);return a};dhx.toArray=function(a){return dhx.extend(a||[],dhx.PowerArray,true)};dhx.toFunctor=function(a){return typeof a=="string"?eval(a):a};dhx.s={};
dhx.event=function(a,b,c,d){a=dhx.toNode(a);var e=dhx.uid();dhx.s[e]=[a,b,c];if(d)c=dhx.bind(c,d);if(a.addEventListener)a.addEventListener(b,c,false);else a.attachEvent&&a.attachEvent("on"+b,c);return e};dhx.eventRemove=function(a){if(a){var b=dhx.s[a];if(b[0].removeEventListener)b[0].removeEventListener(b[1],b[2],false);else b[0].detachEvent&&b[0].detachEvent("on"+b[1],b[2]);delete this.s[a]}};
dhx.EventSystem={h:function(){this.s={};this.ia={};this.Ta={}},block:function(){this.s.fb=true},unblock:function(){this.s.fb=false},mapEvent:function(a){dhx.extend(this.Ta,a,true)},callEvent:function(a,b){if(this.s.fb)return true;a=a.toLowerCase();var c=this.s[a.toLowerCase()],d=true;if(c)for(var e=0;e<c.length;e++)if(c[e].apply(this,b||[])===false)d=false;if(this.Ta[a]&&!this.Ta[a].callEvent(a,b))d=false;return d},attachEvent:function(a,b,c){a=a.toLowerCase();c=c||dhx.uid();b=dhx.toFunctor(b);var d=
this.s[a]||dhx.toArray();d.push(b);this.s[a]=d;this.ia[c]={f:b,t:a};return c},detachEvent:function(a){var b=this.ia[a].t,c=this.ia[a].f;b=this.s[b];b.remove(c);delete this.ia[a]}};dhx.extend(dhx,dhx.EventSystem);
dhx.PowerArray={removeAt:function(a,b){if(a>=0)this.splice(a,b||1)},remove:function(a){this.removeAt(this.find(a))},insertAt:function(a,b){if(!b&&b!==0)this.push(a);else{var c=this.splice(b,this.length-b);this[b]=a;this.push.apply(this,c)}},find:function(a){for(i=0;i<this.length;i++)if(a==this[i])return i;return-1},each:function(a,b){for(var c=0;c<this.length;c++)a.call(b||this,this[c])},map:function(a,b){for(var c=0;c<this.length;c++)this[c]=a.call(b||this,this[c]);return this}};dhx.env={};
(function(){if(navigator.userAgent.indexOf("Mobile")!=-1)dhx.env.mobile=true;if(dhx.env.mobile||navigator.userAgent.indexOf("iPad")!=-1)dhx.env.touch=true;if(navigator.userAgent.indexOf("Opera")!=-1)dhx.env.isOpera=true;else{dhx.env.isIE=!!document.all;dhx.env.isFF=!document.all;dhx.env.isWebKit=navigator.userAgent.indexOf("KHTML")!=-1}dhx.env.transform=false;dhx.env.transition=false;var a={};a.names=["transform","transition"];a.transform=["transform","WebkitTransform","MozTransform","oTransform"];
a.transition=["transition","WebkitTransition","MozTransition","oTransition"];for(var b=document.createElement("DIV"),c=0;c<a.names.length;c++)for(;p=a[a.names[c]].pop();)if(typeof b.style[p]!="undefined")dhx.env[a.names[c]]=true})();dhx.env.transform_prefix=function(){var a;if(dhx.env.isOpera)a="-o-";else{a="";if(dhx.env.isFF)a="-moz-";if(dhx.env.isWebKit)a="-webkit-"}return a}();dhx.env.svg=function(){return document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")}();
dhx.html={create:function(a,b,c){b=b||{};var d=document.createElement(a);for(var e in b)d.setAttribute(e,b[e]);if(b.style)d.style.cssText=b.style;if(b["class"])d.className=b["class"];if(c)d.innerHTML=c;return d},getValue:function(a){a=dhx.toNode(a);if(!a)return"";return dhx.isNotDefined(a.value)?a.innerHTML:a.value},remove:function(a){if(a instanceof Array)for(var b=0;b<a.length;b++)this.remove(a[b]);else a&&a.parentNode&&a.parentNode.removeChild(a)},insertBefore:function(a,b,c){if(a)b?b.parentNode.insertBefore(a,
b):c.appendChild(a)},locate:function(a,b){if(a.tagName)var c=a;else{a=a||event;c=a.target||a.srcElement}for(;c;){if(c.getAttribute){var d=c.getAttribute(b);if(d)return d}c=c.parentNode}return null},offset:function(a){if(a.getBoundingClientRect){var b=a.getBoundingClientRect(),c=document.body,d=document.documentElement,e=window.pageYOffset||d.scrollTop||c.scrollTop,f=window.pageXOffset||d.scrollLeft||c.scrollLeft,g=d.clientTop||c.clientTop||0,h=d.clientLeft||c.clientLeft||0,i=b.top+e-g,j=b.left+f-
h;return{y:Math.round(i),x:Math.round(j)}}else{for(j=i=0;a;){i+=parseInt(a.offsetTop,10);j+=parseInt(a.offsetLeft,10);a=a.offsetParent}return{y:i,x:j}}},pos:function(a){a=a||event;if(a.pageX||a.pageY)return{x:a.pageX,y:a.pageY};var b=dhx.env.isIE&&document.compatMode!="BackCompat"?document.documentElement:document.body;return{x:a.clientX+b.scrollLeft-b.clientLeft,y:a.clientY+b.scrollTop-b.clientTop}},preventEvent:function(a){a&&a.preventDefault&&a.preventDefault();dhx.html.stopEvent(a)},stopEvent:function(a){(a||
event).cancelBubble=true;return false},addCss:function(a,b){a.className+=" "+b},removeCss:function(a,b){a.className=a.className.replace(RegExp(b,"g"),"")}};dhx.ready=function(a){this.Jc?a.call():this.Ga.push(a)};dhx.Ga=[];
(function(){var a=document.getElementsByTagName("SCRIPT");if(a.length){a=(a[a.length-1].getAttribute("src")||"").split("/");a.splice(a.length-1,1);dhx.codebase=a.slice(0,a.length).join("/")+"/"}dhx.event(window,"load",function(){dhx.Jc=true;for(var b=0;b<dhx.Ga.length;b++)dhx.Ga[b].call();dhx.Ga=[]})})();dhx.ui={};dhx.ui.zIndex=function(){return dhx.ui.eb++};dhx.ui.eb=1;
(function(){var a=dhx.Touch={longTouchDelay:1E3,deltaStep:30,stepSize:5,speed:"2000ms",finish:"500ms",scale:5,init:function(){if(dhx.env.touch){dhx.event(document.body,"touchstart",a.Sb);dhx.event(document.body,"touchmove",a.Ka);dhx.event(document.body,"touchend",a.Rb)}else{this.Qa=this.nc;dhx.event(document.body,"mousedown",a.Sb);dhx.event(document.body,"mousemove",a.Ka);dhx.event(document.body,"mouseup",a.Rb)}},Rb:function(){if(a.w){if(!a.L)if(a.qa&&dhx.env.touch){var b=document.createEvent("MouseEvent");
b.initMouseEvent("click",true,true,window,false,0,0,0,0,false,false,false,false,0,a.w.target);a.w.target.dispatchEvent(b)}else if(a.ta&&!a.sa)a.db("onSwipeX");else a.sa&&!a.ta&&a.db("onSwipeY");a.ra||dhx.html.remove(a.L||a.aa);a.Mb()}},scrollEnd:function(){if(!a.L){dhx.html.remove(this);a.aa=null}a.ra=false},sb:function(){if(a.L){var b=a.speed,c=a.p.Nb,d=a.p.Ob;a.lb(a.p);if(a.v=="x"){c+=-(a.w.x-a.fa.x)*a.scale;if(c>0){c=0;b=a.finish}else{var e=a.n.dx-a.n.px;if(e+c<0){c=-e;b=a.finish}}a.ra=Math.abs(c-
a.p.Nb)>a.stepSize}if(a.v=="y"){var f=a.ra=Math.abs(f)>a.stepSize;d+=-(a.w.y-a.fa.y)*a.scale;if(d>0){d=0;b=a.finish}else{e=a.n.dy-a.n.py;if(e+d<0){d=-e;b=a.finish}}a.ra=Math.abs(d-a.p.Ob)/a.scale>a.stepSize}a.setMatrix(a.p,{e:c,f:d},b);a.Hb(c,d,b)}else if(a.n){dhx.html.remove(a.aa);a.aa=a.L=dhx.html.create("DIV",{"class":"dhx_scroll_"+a.v},"");if(a.v=="y"){if(a.n.dy-a.n.py<2)return this.v=false;var g=a.n.py*a.n.py/a.n.dy-4;a.L.style.height=g+"px"}else{if(a.n.dx-a.n.px<2)return this.v=false;g=a.n.px*
a.n.px/a.n.dx-4;a.L.style.width=g+"px"}a.p.parentNode.appendChild(a.L);a.L.addEventListener("webkitTransitionEnd",a.scrollEnd,false);if(!a.p.scroll_enabled){a.p.scroll_enabled=true;a.p.parentNode.style.position="relative";a.p.style.cssText+="-webkit-transition: -webkit-transform; -webkit-user-select:none; -webkit-transform-style:flat;"}var h=a.lb(a.p);a.p.Nb=h.e;a.p.Ob=h.f;a.Hb(h.e,h.f);window.setTimeout(a.sb,1)}},Hb:function(b,c,d){d=d||0;var e=a.n.px/a.n.dx*-b,f=a.n.py/a.n.dy*-c;a.setMatrix(a.L,
{e:e,f:f},d)},Ka:function(b){if(a.w){a.fa=a.Qa(b);delta=a.pc();if(a.v)a.sb(true);else{if(Math.abs(delta.x)>a.deltaStep){a.sa=false;if(a.qa){a.Sa();if(a.v=="y")a.v=false}}if(Math.abs(delta.y)>a.deltaStep){a.ta=false;if(a.qa){a.Sa();if(a.v=="x")a.v=false}}a.v&&a.Ka(b)}}},pc:function(){return{x:a.w.x-a.fa.x,y:a.w.y-a.fa.y}},Xc:function(b){a.tb(a.w.target,"touch_scroll");if(a.p&&a.aa&&a.p.parentNode==a.aa.parentNode){a.Sa();a.Ka(b)}else a.v=a.p=a.n=null},tb:function(b,c){if(dhx.env.touch||dhx.env.isWebKit)for(;b&&
b.getAttribute&&b.tagName!="BODY";){var d=b.getAttribute(c);if(d){a.v=d;a.p=b;a.n={dx:b.offsetWidth,dy:b.offsetHeight,px:b.parentNode.offsetWidth,py:b.parentNode.offsetHeight};return}b=b.parentNode}},Sa:function(){window.clearTimeout(a.ub);a.qa=false;a.tb(a.w.target,"touch_scroll")},Sb:function(b){a.w=a.Qa(b);a.ub=window.setTimeout(a.vc,a.longTouchDelay);a.qa=true;a.sa=true;a.ta=true;a.aa&&a.Xc(b);if(dhx.env.touch)return dhx.html.preventEvent(b)},vc:function(){a.db("onLongTouch");dhx.callEvent("onClick",
[]);a.Mb()},Mb:function(){a.sa=a.ta=a.qa=a.w=a.fa=null;a.L=a.n=a.v=a.p=null;window.clearTimeout(a.ub)},Qa:function(b){return{target:b.target,x:b.touches[0].pageX,y:b.touches[0].pageY}},nc:function(b){return{target:b.target,x:b.pageX,y:b.pageY}},db:function(b){dhx.callEvent(b,[a.w]);var c=dhx.ui.get(a.w);c&&c.callEvent&&c.callEvent(b,[a.w])},lb:function(b){var c=window.getComputedStyle(b).webkitTransform;return c=="none"?{e:0,f:0}:new WebKitCSSMatrix(c)},setMatrix:function(b,c,d){b.style.webkitTransform=
"translate("+Math.round(c.e)+"px,"+Math.round(c.f)+"px)";b.style.webkitTransitionDuration=d}};dhx.TouchEvents={h:function(){this.attachEvent("onSwipeX",this.Yc);this.attachEvent("onBeforeSelect",this.unSwipe);this.attachEvent("onAfterDelete",this.unSwipe)},Yc:function(b){if((b=this.locate(b))&&b!=this.Z){this.unSwipe();this.swipe(b)}},swipe:function(b){this.Z=b;this.get(this.Z).$template="swipe";this.refresh(this.Z)},unSwipe:function(){if(this.Z){var b=this.get(this.Z);if(b){b.$template="";this.refresh(this.Z)}this.Z=
null}}};dhx.ready(function(){a.init()})})();
dhx.DragControl={J:dhx.toArray(["dummy"]),addDrop:function(a,b,c){a=dhx.toNode(a);a.dhx_drop=this.jb(b);if(c)a.dhx_master=true},jb:function(a){a=a||dhx.DragControl;var b=this.J.find(a);if(b<0){b=this.J.length;this.J.push(a)}return b},addDrag:function(a,b){a=dhx.toNode(a);a.dhx_drag=this.jb(b);dhx.event(a,"mousedown",this.Ic,a)},Ic:function(a){if(dhx.DragControl.M){dhx.DragControl.Ya();dhx.DragControl.destroyDrag()}dhx.DragControl.M=this;dhx.DragControl.ga=dhx.event(document.body,"mousemove",dhx.DragControl.Vc);
dhx.DragControl.ha=dhx.event(document.body,"mouseup",dhx.DragControl.Ya);a.cancelBubble=true;return false},Ya:function(){dhx.DragControl.ga=dhx.eventRemove(dhx.DragControl.ga);dhx.DragControl.ha=dhx.eventRemove(dhx.DragControl.ha)},Vc:function(a){dhx.DragControl.Ya();if(dhx.DragControl.createDrag(a)){dhx.DragControl.sendSignal("start");dhx.DragControl.ga=dhx.event(document.body,"mousemove",dhx.DragControl.yb);dhx.DragControl.ha=dhx.event(document.body,"mouseup",dhx.DragControl.Wc);dhx.DragControl.yb(a)}},
Wc:function(a){dhx.DragControl.ga=dhx.eventRemove(dhx.DragControl.ga);dhx.DragControl.ha=dhx.eventRemove(dhx.DragControl.ha);if(dhx.DragControl.A){dhx.DragControl.onDrop(dhx.DragControl.M,dhx.DragControl.A,this.xa,a);dhx.DragControl.onDragOut(dhx.DragControl.M,dhx.DragControl.A,null,a)}dhx.DragControl.destroyDrag();dhx.DragControl.sendSignal("stop")},yb:function(a){var b=dhx.html.pos(a);dhx.DragControl.C.style.top=b.y+dhx.DragControl.top+"px";dhx.DragControl.C.style.left=b.x+dhx.DragControl.left+
"px";if(dhx.DragControl.Jb)dhx.DragControl.Jb=false;else dhx.DragControl.fc(a.srcElement||a.target,a);a.cancelBubble=true;return false},fc:function(a,b){for(;a&&a.tagName!="BODY";){if(a.dhx_drop){if(this.A&&(this.A!=a||a.dhx_master))this.onDragOut(this.M,this.A,a,b);if(!this.A||this.A!=a||a.dhx_master){this.A=null;if(this.xa=this.onDragIn(dhx.DragControl.M,a,b))this.A=a;return}return}a=a.parentNode}if(this.A)this.A=this.xa=this.onDragOut(this.M,this.A,null,b)},sendSignal:function(a){dhx.DragControl.active=
a=="start"},getMaster:function(a){return this.J[a.dhx_drag||a.dhx_drop]},getContext:function(){return this.hb},getNode:function(){return this.C},createDrag:function(a){var b=dhx.DragControl.M,c=this.J[b.dhx_drag],d;if(c.onDragCreate){d=c.onDragCreate(b,a);d.style.position="absolute";d.style.zIndex=dhx.ui.zIndex();d.onmousemove=dhx.DragControl.Kb}else{var e=dhx.DragControl.onDrag(b,a);if(!e)return false;d=document.createElement("DIV");d.innerHTML=e;d.className="dhx_drag_zone";d.onmousemove=dhx.DragControl.Kb;
document.body.appendChild(d)}dhx.DragControl.C=d;return true},Kb:function(){dhx.DragControl.Jb=true},destroyDrag:function(){var a=dhx.DragControl.M,b=this.J[a.dhx_drag];b&&b.onDragDestroy?b.onDragDestroy(a,dhx.DragControl.C):dhx.html.remove(dhx.DragControl.C);dhx.DragControl.xa=dhx.DragControl.M=dhx.DragControl.A=dhx.DragControl.C=null},top:5,left:5,onDragIn:function(a,b,c){var d=this.J[b.dhx_drop];if(d.onDragIn&&d!=this)return d.onDragIn(a,b,c);b.className+=" dhx_drop_zone";return b},onDragOut:function(a,
b,c,d){var e=this.J[b.dhx_drop];if(e.onDragOut&&e!=this)return e.onDragOut(a,b,c,d);b.className=b.className.replace("dhx_drop_zone","");return null},onDrop:function(a,b,c,d){var e=this.J[b.dhx_drop];dhx.DragControl.hb.from=dhx.DragControl.getMaster(a);if(e.onDrop&&e!=this)return e.onDrop(a,b,c,d);b.appendChild(a)},onDrag:function(a,b){var c=this.J[a.dhx_drag];if(c.onDrag&&c!=this)return c.onDrag(a,b);dhx.DragControl.hb={source:a,from:a};return"<div style='"+a.style.cssText+"'>"+a.innerHTML+"</div>"}};
dhx.Movable={move_setter:function(a){if(a){this.Ba=dhx.copy(this.Ba);this.Ba.master=this;dhx.DragControl.addDrag(this.q,this.Ba)}},Ba:{onDragCreate:function(a,b){var c=dhx.html.offset(a);a=dhx.html.pos(b);dhx.DragControl.top=c.y-a.y;dhx.DragControl.left=c.x-a.x;return dhx.toNode(this.master.b)},onDragDestroy:function(){}}};
dhx.Scrollable={h:function(){this.j.appendChild(dhx.html.create("DIV",{"class":"dhx_scroll_cont"},""));this.j=this.j.firstChild},scroll_setter:function(a){if(!a)return false;if(dhx.Touch){this.j.setAttribute("touch_scroll","y");this.attachEvent("onBeforeRender",dhx.bind(this.Kc,this));return false}else{this.j.parentNode.style.overflowY=a?"scroll":"";return true}},Kc:function(){dhx.Touch.scrollEnd();dhx.Touch.setMatrix(this.j,{e:0,f:0},0)}};
dhx.EditAbility={h:function(){this.va=this.K=null;this.attachEvent("onEditKeyPress",function(a,b,c){if(a==13&&!c)this.stopEdit();else a==27&&this.stopEdit(true)});this.attachEvent("onBeforeRender",function(){this.stopEdit()})},isEdit:function(){return this.K},edit:function(a){if(this.stopEdit(false,a))if(this.callEvent("onBeforeEditStart",[a])){var b=this.data.get(a);if(!b.$template){b.$template="edit";this.data.refresh(a);this.K=a;this.Oc(a);this.va(true,b);this.callEvent("onAfterEditStart",[a])}}},
stopEdit:function(a,b){if(!this.K)return true;if(this.K==b)return false;if(!this.callEvent("onBeforeEditStop",[this.K]))return false;var c=this.data.get(this.K);c.$template=null;a||this.va(false,c);a=this.K;this.va=this.K=null;this.data.refresh(a);this.callEvent("onAfterEditStop",[a]);return true},Oc:function(a){var b=this.o(a),c="",d="",e=[];if(b){var f=b.getElementsByTagName("*"),g="";for(a=0;a<f.length;a++)if(f[a].nodeType==1&&(g=f[a].getAttribute("bind"))){c+="els["+e.length+"].value="+g+";";
d+=g+"=els["+e.length+"].value;";e.push(f[a]);f[a].className+=" dhx_allow_selection";f[a].onselectstart=this.bc}f=null}c=Function("obj","els",c);d=Function("obj","els",d);this.va=function(h,i){if(h){c(i,e);e.length&&e[0].select&&e[0].select()}else d(i,e)}},bc:function(a){return(a||event).cancelBubble=true}};dhx.onKeyPressedTimeout=200;
dhx.KeyEvents={h:function(){dhx.event(this.c,"keyup",this.Dc,this)},Dc:function(a){a=a||event;var b=a.which||a.keyCode;this.callEvent(this.K?"onEditKeyPress":"onKeyPress",[b,a.ctrlKey,a.shiftKey,a]);var c=this;window.setTimeout(function(){c.callEvent(c.K?"onEditKeyPressed":"onKeyPressed",[])},dhx.onKeyPressedTimeout)}};
dhx.MouseEvents={h:function(){if(this.on_click){dhx.event(this.c,"click",this.Ac,this);dhx.event(this.c,"contextmenu",this.Bc,this)}this.on_dblclick&&dhx.event(this.c,"dblclick",this.Cc,this);if(this.on_mouse_move){dhx.event(this.c,"mousemove",this.zb,this);dhx.event(this.c,dhx.env.isIE?"mouseleave":"mouseout",this.zb,this)}},Ac:function(a){return this.Ua(a,this.on_click,"ItemClick")},Cc:function(a){return this.Ua(a,this.on_dblclick,"ItemDblClick")},Bc:function(a){var b=dhx.html.locate(a,this.r);
if(b&&!this.callEvent("onBeforeContextMenu",[b,a]))return dhx.html.preventEvent(a)},zb:function(a){if(dhx.env.isIE)a=document.createEventObject(event);this.xb&&window.clearTimeout(this.xb);this.callEvent("onMouseMoving",[a]);this.xb=window.setTimeout(dhx.bind(function(){a.type=="mousemove"?this.Ec(a):this.Fc(a)},this),500)},Ec:function(a){this.Ua(a,this.on_mouse_move,"MouseMove")||this.callEvent("onMouseOut",[a||event])},Fc:function(a){this.callEvent("onMouseOut",[a||event])},Ua:function(a,b,c){a=
a||event;for(var d=a.target||a.srcElement,e="",f=null,g=false;d&&d.parentNode;){if(!g&&d.getAttribute)if(f=d.getAttribute(this.r)){d.getAttribute("userdata")&&this.callEvent("onLocateData",[f,d]);if(!this.callEvent("on"+c,[f,a,d]))return;g=true}if(e=d.className){e=e.split(" ");e=e[0]||e[1];if(b[e]&&b[e].call(this,a,f,d)!==true)return}d=d.parentNode}return g}};
dhx.SelectionModel={h:function(){this.m=dhx.toArray();this.data.attachEvent("onStoreUpdated",dhx.bind(this.ic,this))},ic:function(a,b,c){if(c=="delete")this.m.remove(a);else if(!this.data.dataCount())this.m=dhx.toArray()},Ia:function(a,b,c){if(!c&&!this.callEvent("onBeforeSelect",[a,b]))return false;this.data.get(a).$selected=b;c?c.push(a):this.Za(a);return true},select:function(a,b,c){if(!a)return this.selectAll();if(a instanceof Array)for(var d=0;d<a.length;d++)this.select(a[d],b,c);else{if(c&&
this.m.length)return this.selectAll(this.m[this.m.length-1],a);if(!b&&(this.m.length!=1||this.m[0]!=a))this.unselectAll();if(this.isSelected(a))b&&this.unselect(a);else if(this.Ia(a,true)){this.m.push(a);this.callEvent("onAfterSelect",[a])}}},unselect:function(a){if(!a)return this.unselectAll();this.isSelected(a)&&this.Ia(a,false)&&this.m.remove(a)},selectAll:function(a,b){var c,d=[];c=a||b?this.data.getRange(a,b):this.data.getRange();c.each(function(e){var f=this.data.get(e.id);if(!f.$selected){this.m.push(e.id);
this.Ia(e.id,true,d)}return e.id},this);this.Za(d)},unselectAll:function(){var a=[];this.m.each(function(b){this.Ia(b,false,a)},this);this.m=dhx.toArray();this.Za(a)},isSelected:function(a){return this.m.find(a)!=-1},getSelected:function(a){switch(this.m.length){case 0:return a?[]:"";case 1:return a?[this.m[0]]:this.m[0];default:return[].concat(this.m)}},tc:function(a){return a.length>100||a.length>this.data.dataCount/2},Za:function(a){if(typeof a!="object")a=[a];if(a.length){if(this.tc(a))this.data.refresh();
else for(var b=0;b<a.length;b++)this.render(a[b],this.data.get(a[b]),"update");this.callEvent("onSelectChange",[a])}}};
(function(){var a={};dhx.Template=function(b){if(typeof b=="function")return b;if(a[b])return a[b];b=(b||"").toString();if(b.indexOf("->")!=-1){b=b.split("->");switch(b[0]){case "html":b=dhx.html.getValue(b[1]).replace(/\"/g,'\\"');break;case "http":b=(new dhx.ajax).sync().get(b[1],{uid:dhx.uid()}).responseText;break;default:break}}b=(b||"").toString();b=b.replace(/(\r\n|\n)/g,"\\n");b=b.replace(/(\")/g,'\\"');b=b.replace(/\{obj\.([^}?]+)\?([^:]*):([^}]*)\}/g,'"+(obj.$1?"$2":"$3")+"');b=b.replace(/\{common\.([^}\(]*)\}/g,
"\"+(common.$1||'')+\"");b=b.replace(/\{common\.([^\}\(]*)\(\)\}/g,'"+(common.$1?common.$1(obj):"")+"');b=b.replace(/\{obj\.([^}]*)\}/g,"\"+(obj.$1||'')+\"");b=b.replace(/#([a-z0-9_\[\]]+)#/gi,"\"+(obj.$1||'')+\"");b=b.replace(/\{obj\}/g,'"+obj+"');b=b.replace(/\{-obj/g,"{obj");b=b.replace(/\{-common/g,"{common");b='return "'+b+'";';return a[b]=Function("obj","common",b)};dhx.Template.empty=function(){return""};dhx.Template.bind=function(b){return dhx.bind(dhx.Template(b),this)};dhx.Type=function(b,
c){if(typeof b=="function")b=b.prototype;if(!b.types){b.types={"default":b.type};b.type.name="default"}var d=c.name,e=b.type;if(d)e=b.types[d]=dhx.copy(b.type);for(var f in c)e[f]=f.indexOf("template")==0?dhx.Template(c[f]):c[f];return d}})();dhx.AtomRender={ca:function(a){return this.a.template(a)},render:function(){if(!this.callEvent||this.callEvent("onBeforeRender",[this.data])){if(this.data)this.j.innerHTML=this.ca(this.data);this.callEvent&&this.callEvent("onAfterRender",[])}},template_setter:dhx.Template};
dhx.SingleRender=dhx.proto({ca:function(a){return this.type.template_start(a,this.type)+this.type.template(a,this.type)+this.type.template_end(a,this.type)},customize:function(a){dhx.Type(this,a)}},dhx.AtomRender);dhx.ajax=function(a,b,c){if(arguments.length!==0){var d=new dhx.ajax;if(c)d.master=c;d.get(a,null,b)}if(!this.getXHR)return new dhx.ajax;return this};
dhx.ajax.prototype={getXHR:function(){return dhx.env.isIE?new ActiveXObject("Microsoft.xmlHTTP"):new XMLHttpRequest},send:function(a,b,c){var d=this.getXHR();if(typeof c=="function")c=[c];if(typeof b=="object"){var e=[];for(var f in b)e.push(f+"="+encodeURIComponent(b[f]));b=e.join("&")}if(b&&!this.post){a=a+(a.indexOf("?")!=-1?"&":"?")+b;b=null}d.open(this.post?"POST":"GET",a,!this.Pb);this.post&&d.setRequestHeader("Content-type","application/x-www-form-urlencoded");if(!this.Pb){var g=this;d.onreadystatechange=
function(){if(!d.readyState||d.readyState==4){if(c&&g)for(var h=0;h<c.length;h++)if(c[h])c[h].call(g.master||g,d.responseText,d.responseXML,d);c=d=g=g.master=null}}}d.send(b||null);return d},get:function(a,b,c){this.post=false;return this.send(a,b,c)},post:function(a,b,c){this.post=true;return this.send(a,b,c)},sync:function(){this.Pb=true;return this}};
dhx.AtomDataLoader={h:function(){this.data={};this.G.push(this.uc)},uc:function(){if(this.a.data)this.parse(this.a.data,this.a.datatype||"json");else if(this.a.url)this.load(this.a.url,this.a.datatype||"json")},load:function(a,b,c){this.callEvent("onXLS",[]);if(typeof b=="string"){this.data.driver=dhx.DataDriver[b];b=c}dhx.ajax(a,[this.Xa,b],this)},parse:function(a,b){this.callEvent("onXLS",[]);this.data.driver=dhx.DataDriver[b||"json"];this.Xa(a,null)},Xa:function(a,b){var c=this.data.driver,d=c.toObject(a,
b);if(c.getTopElement)d=c.getTopElement(d);this.data=c?c.getDetails(d):a;this.callEvent("onXLE",[])}};dhx.DataDriver={};dhx.DataDriver.json={toObject:function(a){a||(a="[]");if(typeof a=="string"){eval("dhx.temp="+a);return dhx.temp}return a},getRecords:function(a){if(a&&!(a instanceof Array))return[a];return a},getDetails:function(a){return a},getInfo:function(a){return{ba:a.total_count||0,V:a.pos||0}}};
dhx.DataDriver.json_ext={toObject:function(a){a||(a="[]");if(typeof a=="string"){eval("var temp="+a);dhx.temp=[];var b=temp.header;for(a=0;a<temp.data.length;a++){for(var c={},d=0;d<b.length;d++)if(typeof temp.data[a][d]!="undefined")c[b[d]]=temp.data[a][d];dhx.temp.push(c)}return dhx.temp}return a},getRecords:function(a){if(a&&!(a instanceof Array))return[a];return a},getDetails:function(a){return a},getInfo:function(a){return{ba:a.total_count||0,V:a.pos||0}}};
dhx.DataDriver.html={toObject:function(a){if(typeof a=="string"){var b=null;if(a.indexOf("<")==-1)b=dhx.toNode(a);if(!b){b=document.createElement("DIV");b.innerHTML=a}return b.getElementsByTagName(this.tag)}return a},getRecords:function(a){if(a.tagName)return a.childNodes;return a},getDetails:function(a){return dhx.DataDriver.xml.tagToObject(a)},getInfo:function(){return{ba:0,V:0}},tag:"LI"};
dhx.DataDriver.jsarray={toObject:function(a){if(typeof a=="string"){eval("dhx.temp="+a);return dhx.temp}return a},getRecords:function(a){return a},getDetails:function(a){for(var b={},c=0;c<a.length;c++)b["data"+c]=a[c];return b},getInfo:function(){return{ba:0,V:0}}};
dhx.DataDriver.csv={toObject:function(a){return a},getRecords:function(a){return a.split(this.row)},getDetails:function(a){a=this.stringToArray(a);for(var b={},c=0;c<a.length;c++)b["data"+c]=a[c];return b},getInfo:function(){return{ba:0,V:0}},stringToArray:function(a){a=a.split(this.cell);for(var b=0;b<a.length;b++)a[b]=a[b].replace(/^[ \t\n\r]*(\"|)/g,"").replace(/(\"|)[ \t\n\r]*$/g,"");return a},row:"\n",cell:","};
dhx.DataDriver.xml={toObject:function(a,b){if(b&&(b=this.checkResponse(a,b)))return b;if(typeof a=="string")return this.fromString(a);return a},getRecords:function(a){return this.xpath(a,this.records)},records:"/*/item",userdata:"/*/userdata",getDetails:function(a){return this.tagToObject(a,{})},getUserData:function(a,b){b=b||{};var c=this.xpath(a,this.userdata);for(a=0;a<c.length;a++){var d=this.tagToObject(c[a]);b[d.name]=d.value}return b},getTopElement:function(a){return a.documentElement},getInfo:function(a){return{ba:a.documentElement.getAttribute("total_count")||
0,V:a.documentElement.getAttribute("pos")||0}},xpath:function(a,b){if(window.XPathResult){var c=a;if(a.nodeName.indexOf("document")==-1)a=a.ownerDocument;var d=[];a=a.evaluate(b,c,null,XPathResult.ANY_TYPE,null);for(c=a.iterateNext();c;){d.push(c);c=a.iterateNext()}return d}else if(a.selectNodes)return a.selectNodes(b);else{d=b.split("/").pop();return a.getElementsByTagName(d)}},tagToObject:function(a,b){b=b||{};var c=a.attributes;if(c)for(var d=0;d<c.length;d++)b[c[d].name]=c[d].value;var e=false,
f=a.childNodes;for(d=0;d<f.length;d++)if(f[d].nodeType==1){var g=f[d].tagName;if(typeof b[g]!="undefined"){b[g]instanceof Array||(b[g]=[b[g]]);b[g].push(this.tagToObject(f[d],{}))}else b[f[d].tagName]=this.tagToObject(f[d],{});e=true}if(c&&!c.length&&!e)return this.nodeValue(a);b.value=this.nodeValue(a);return b},nodeValue:function(a){if(a.firstChild)return a.firstChild.data;return""},fromString:function(a){if(window.DOMParser)return(new DOMParser).parseFromString(a,"text/xml");if(window.ActiveXObject){temp=
new ActiveXObject("Microsoft.xmlDOM");temp.loadXML(a);return temp}},checkResponse:function(a,b){if(b&&b.firstChild&&b.firstChild.tagName!="parsererror")return b;if(a=this.from_string(a.responseText.replace(/^[\s]+/,"")))return a}};
dhx.Settings={h:function(){this.a=this.config={}},define:function(a,b){if(typeof a=="object")return this.Ab(a);return this.gb(a,b)},gb:function(a,b){var c=this[a+"_setter"];return this.a[a]=c?c.call(this,b,a):b},Ab:function(a){if(a)for(var b in a)this.gb(b,a[b])},ma:function(a,b){var c=dhx.extend({},b);typeof a=="object"&&!a.tagName&&dhx.extend(c,a,true);this.Ab(c)},Aa:function(a,b){for(var c in b)switch(typeof a[c]){case "object":a[c]=this.Aa(a[c]||{},b[c]);break;case "undefined":a[c]=b[c];break;
default:break}return a}};dhx.Destruction={h:function(){dhx.destructors.push(this)},destructor:function(){this.destructor=function(){};this.X=this.u=null;this.C&&document.body.appendChild(this.C);this.C=null;if(this.c){this.c.innerHTML="";this.c.u=null}this.data=this.c=this.j=null;this.s=this.ia={}}};dhx.destructors=[];
dhx.event(window,"unload",function(){for(var a=0;a<dhx.destructors.length;a++)dhx.destructors[a].destructor();dhx.destructors=[];for(var b in dhx.s){a=dhx.s[b];if(a[0].removeEventListener)a[0].removeEventListener(a[1],a[2],false);else a[0].detachEvent&&a[0].detachEvent("on"+a[1],a[2]);delete dhx.s[b]}});
(function(){var a=dhx.ui=function(d){if(!d.id)d.id=dhx.uid();var e=dhx.toNode(d.container||document.body),f=a.pa(d);e.appendChild(f.b);f.resize();e.tagName.toLowerCase()=="body"&&dhx.event(window,"resize",dhx.bind(f.resize,f));return f};dhx.ui.zIndex=function(){return dhx.ui.eb++};dhx.ui.eb=1;var b=a.map={};a.pa=function(d){if(d.view){var e=d.view;delete d.view;return new b[e](d)}else if(d.rows||d.cols)return new b.layout(d);else if(d.content)return new b.content(d);else if(d.template)return new b.template(d);
else{if(typeof d=="string")return new b.template({template:d});return new b.view(d)}};a.views={};a.get=function(d){if(a.views[d])return a.views[d];var e=d;if(typeof d=="object")e=d.target||d.srcElement;return a.views[dhx.html.locate({target:dhx.toNode(e)},"view_id")]};if(dhx.isNotDefined(window.$$))$$=a.get;b.view=a.view=dhx.proto({h:function(){this.name="View";this.version="3.0";this.c=this.b=dhx.html.create("DIV",{"class":"dhx_view"})},defaults:{width:-1,height:-1,gravity:1},getNode:function(){return this.b},
getParent:function(){return this.la||null},container_setter:function(d){dhx.toNode(d).appendChild(this.b);return true},css_setter:function(d){this.b.className+=" "+d},id_setter:function(d){a.views[d]=this;this.b.setAttribute("view_id",d);return d},g:function(d,e){if(this.ja&&this.ja[0]==d&&this.ja[1]==e)return false;this.ja=[d,e];this.O=d;this.N=e;this.b.style.width=d+"px";this.b.style.height=e+"px";return true},i:function(){var d=this.a.width,e=this.a.height,f,g;f=g=this.a.gravity;if(d==-1)d=0;else{f=
0;d+=this.a.scroll?18:0}if(e==-1)e=0;else g=0;return[f,d,g,e]},show:function(){this.getParent()&&this.getParent().Ib(this)},resize:function(){if(this.la)var d=this.O,e=this.N;else{d=this.b.parentNode.offsetWidth;e=this.b.parentNode.offsetHeight}var f=this.i();d=f[0]?Math.max(d,f[1]):Math.max(f[1],d);e=f[2]?Math.max(e,f[3]):Math.max(f[3],e);this.g(d,e)}},dhx.Settings,dhx.Destruction);var c=a.view.prototype;b.layout=a.layout=dhx.proto({h:function(){this.name="Layout";this.G.push(this.H)},rows_setter:function(d){this.F=
1;this.T=d},cols_setter:function(d){this.F=0;this.T=d},replace:function(d,e){var f=dhx.PowerArray.find.call(this.d,d);d.b.parentNode.insertBefore(e.b,d.b);e.b.style.cssFloat=d.b.style.cssFloat;dhx.html.remove(d.b);this.d[f]=e;this.d[f].la=this},reconstruct:function(){for(var d=0;d<this.d.length;d++)dhx.html.remove(this.d[d].b);this.H();this.resize()},H:function(d){d=this.T||d;this.T=null;this.d=[];this.b.style.verticalAlign="top";for(var e=0;e<d.length;e++){this.d[e]=a.pa(d[e]);this.d[e].la=this;
if(!this.F)this.d[e].b.style.cssFloat="left";this.b.appendChild(this.d[e].b)}},i:function(){var d=0,e=0,f=0,g=0;this.S=[];for(var h=0;h<this.d.length;h++){var i=this.S[h]=this.d[h].i();if(this.F){d=Math.max(d,i[1]);f=Math.max(f,i[0]);e+=i[3];g+=i[2]}else{e=Math.max(e,i[3]);g=Math.max(g,i[2]);d+=i[1];f+=i[0]}}this.za=[f,d,g,e];if(this.a.height>-1){e=this.a.height;g=0}if(this.a.width>-1){d=this.a.width;f=0}if(this.F){if(d)f=0;if(g)e=0}else{if(e)g=0;if(f)d=0}return[f,d,g,e]},g:function(d,e){c.g.call(this,
d,e);this.ab(d,e)},ab:function(d,e){for(var f=d-this.za[1],g=e-this.za[3],h=this.za[0],i=this.za[2],j=0;j<this.d.length;j++){if(this.F){var l=d,k;if(this.S[j][2]){k=Math.round(this.S[j][2]*g/i);g-=k;i-=this.S[j][2]}else k=this.S[j][3]}else{k=e;if(this.S[j][0]){l=Math.round(this.S[j][0]*f/h);f-=l;h-=this.S[j][0]}else l=this.S[j][1]}this.d[j].g(l,k)}}},a.view);b.debug=a.debug_view=dhx.proto({h:function(){this.c=dhx.html.create("DIV");this.b.appendChild(this.c);this.c.style.border="2px inset silver"},
g:function(d,e){if(c.g.call(this,d-1,e)){this.O=d-4;this.N=e-4;this.c.style.width=d-4+"px";this.c.style.height=e-4+"px";return true}return false}},a.view);b.touch=a.touch_view=dhx.proto({h:function(){this.c.style.border="1px solid #AEAEAE"},i:function(){var d=this.a.k,e=c.i.call(this);if(!d)return e;var f=(d.left?0:1)+(d.right?0:1);d=(d.top?0:1)+(d.bottom?0:1);if(e[1]&&f)e[1]+=f;if(e[3]&&d)e[3]+=d;return e},g:function(d,e){var f=this.a.k;if(f){d-=(f.left?0:1)+(f.right?0:1);e-=(f.top?0:1)+(f.bottom?
0:1)}else this.c.style.border="0px solid #AEAEAE";return c.g.call(this,d,e)}},a.view);dhx.ui.border_layout=b.border_layout=dhx.proto({h:function(){},H:function(){this.b.className+=" dhx_layout_"+(this.a.type||"");var d=this.T;if(!this.a.k)this.a.k={top:true,left:true,right:true,bottom:true};for(var e=0;e<d.length;e++)d[e].k=dhx.copy(this.a.k);var f=false;if(this.a.type=="clean")f=true;if(this.F){for(e=1;e<d.length-1;e++)d[e].k.top=d[e].k.bottom=f;if(this.a.type!="head")d[0].k.bottom=f;d[d.length-
1].k.top=f}else{for(e=1;e<d.length-1;e++)d[e].k.left=d[e].k.right=f;if(this.a.type!="head")d[0].k.right=f;d[d.length-1].k.left=f}a.layout.prototype.H.call(this,d);for(e=0;e<d.length;e++){var g=this.d[e];if(!g.d){f=g.a.k;if(f.top)g.b.style.borderTopWidth="0px";if(f.left)g.b.style.borderLeftWidth="0px";if(f.right)g.b.style.borderRightWidth="0px";if(f.bottom)g.b.style.borderBottomWidth="0px"}}if(this.F)for(e=1;e<d.length;e++)this.d[e].b.style.marginTop=this.ka+"px";else for(e=1;e<d.length;e++)this.d[e].b.style.marginLeft=
this.ka+"px"},i:function(){var d=dhx.ui.layout.prototype.i.call(this),e=this.ka*(this.d.length-1);if(this.F){if(d[3])d[3]+=e}else if(d[1])d[1]+=e;return d},g:function(d,e){c.g.call(this,d,e);var f=this.ka*(this.d.length-1);if(this.F)e-=f;else d-=f;a.layout.prototype.ab.call(this,d,e)},type_setter:function(d){this.ka=this.wc[d];return d},wc:{wide:4,clean:0,head:4,line:0},ka:-1},b.layout);b.layout=b.border_layout;b.view=window.DHTMLX_SKIN?b[DHTMLX_SKIN]:b.touch;b.template=dhx.ui.template_view=dhx.proto({h:function(){this.name=
"Template";this.j=this.c;this.attachEvent("onXLE",this.render);this.G.push(this.render)},defaults:{template:dhx.Template.empty}},b.view,dhx.AtomDataLoader,dhx.AtomRender,dhx.EventSystem);b.iframe=dhx.ui.iframe_view=dhx.proto({defaults:{loading:true},h:function(){this.name="Iframe";this.j=this.c;this.c.innerHTML="<div class='dhx_loading_cover' style='display:none'></div><iframe style='width:100%; height:100%' frameborder='0' src='about:blank'></iframe>"},src_setter:function(d){this.c.childNodes[1].src=
d;if(d.indexOf("http")&&this.a.loading){this.c.childNodes[0].style.display="block";dhx.delay(this.Tc,this)}return d},Tc:function(){try{if(this.getWindow().document.body)this.c.childNodes[0].style.display="none";else this.c.childNodes[1].onload = dhx.bind(function(){this.c.childNodes[0].style.display="none"},this)}catch(d){}},getWindow:function(){return this.c.childNodes[1].contentWindow}},b.view);b.content=dhx.ui.content_view=dhx.proto({ma:function(){c.ma.apply(this,arguments);this.a.content&&
this.c.appendChild(dhx.toNode(this.a.content))}},b.view)})();
dhx.DataLoader=dhx.proto({h:function(a){a=a||"";this.data=a.datastore||new dhx.DataStore},load:function(a){dhx.AtomDataLoader.load.apply(this,arguments);if(!this.data.feed)this.data.feed=function(b,c){if(this.ya)return this.ya=[b,c];else this.ya=true;this.load(a+(a.indexOf("?")==-1?"?":"&")+"posStart="+b+"&count="+c,function(){var d=this.ya;this.ya=false;typeof d=="object"&&this.data.feed.apply(this,d)})}},Xa:function(a,b){this.data.Gc(this.data.driver.toObject(a,b));this.callEvent("onXLE",[])}},
dhx.AtomDataLoader).prototype;dhx.DataStore=function(){this.name="DataStore";dhx.extend(this,dhx.EventSystem);this.setDriver("xml");this.pull={};this.order=dhx.toArray();this.Ub=false};
dhx.DataStore.prototype={setDriver:function(a){this.driver=dhx.DataDriver[a]},Tb:function(a){if(a.item){if(!(a.item instanceof Array))a.item=[a.item];for(var b=0;b<a.item.length;b++){var c=a.item[b],d=this.id(c);a.item[b]=d;this.pull[d]=c;c.parent=a.id;c.level=a.level+1;this.Tb(c)}}},Gc:function(a){for(var b=this.driver.getInfo(a),c=this.driver.getRecords(a),d=(b.V||0)*1,e=0,f=0;f<c.length;f++){var g=this.driver.getDetails(c[f]),h=this.id(g);if(!this.pull[h]){this.order[e+d]=h;e++}this.pull[h]=g;
if(this.Ub){g.level=1;this.Tb(g)}}for(f=0;f<b.ba;f++)if(!this.order[f]){h=dhx.uid();g={id:h,$template:"loading"};this.pull[h]=g;this.order[f]=h}this.callEvent("onStoreLoad",[this.driver,a]);this.refresh()},id:function(a){return a.id||(a.id=dhx.uid())},get:function(a){return this.pull[a]},set:function(a,b){if(this.callEvent("onBeforeUpdate",[a,b])===false)return false;this.pull[a]=b;this.refresh(a)},refresh:function(a){a?this.callEvent("onStoreUpdated",[a,this.pull[a],"update"]):this.callEvent("onStoreUpdated",
[null,null,null])},getRange:function(a,b){if(arguments.length){a=this.indexById(a);b=this.indexById(b);if(a>b){var c=b;b=a;a=c}}else{a=this.min||0;b=Math.min(this.max||Infinity,this.dataCount()-1)}return this.getIndexRange(a,b)},getIndexRange:function(a,b){b=Math.min(b,this.dataCount()-1);var c=dhx.toArray();for(a=a;a<=b;a++)c.push(this.get(this.order[a]));return c},dataCount:function(){return this.order.length},exists:function(a){return!!this.pull[a]},move:function(a,b){if(!(a<0||b<0)){var c=this.idByIndex(a),
d=this.get(c);this.order.removeAt(a);this.order.insertAt(c,Math.min(this.order.length,b));this.callEvent("onStoreUpdated",[c,d,"move"])}},add:function(a,b){var c=this.id(a),d=this.dataCount();if(dhx.isNotDefined(b)||b<0)b=d;if(b>d)b=Math.min(this.order.length,b);if(this.callEvent("onBeforeAdd",[c,a,b])===false)return false;if(this.exists(c))return null;this.pull[c]=a;this.order.insertAt(c,b);if(this.P){var e=this.P.length;if(!b&&this.order.length)e=0;this.P.insertAt(c,e)}this.callEvent("onafterAdd",
[c,b]);this.callEvent("onStoreUpdated",[c,a,"add"]);return c},remove:function(a){if(a instanceof Array)for(var b=0;b<a.length;b++)this.remove(a[b]);else{if(this.callEvent("onBeforeDelete",[a])===false)return false;if(!this.exists(a))return null;b=this.get(a);this.order.remove(a);this.P&&this.P.remove(a);delete this.pull[a];this.callEvent("onafterdelete",[a]);this.callEvent("onStoreUpdated",[a,b,"delete"])}},clearAll:function(){this.pull={};this.order=dhx.toArray();this.P=null;this.callEvent("onClearAll",
[]);this.refresh()},idByIndex:function(a){return this.order[a]},indexById:function(a){return a=this.order.find(a)},next:function(a,b){return this.order[this.indexById(a)+(b||1)]},first:function(){return this.order[0]},last:function(){return this.order[this.order.length-1]},previous:function(a,b){return this.order[this.indexById(a)-(b||1)]},sort:function(a,b,c){var d=a;if(typeof a=="function")d={as:a,dir:b};else if(typeof a=="string")d={by:a,dir:b,as:c};var e=[d.by,d.dir,d.as];if(this.callEvent("onbeforesort",
e)){if(this.order.length){var f=dhx.sort.create(d),g=this.getRange(this.first(),this.last());g.sort(f);this.order=g.map(function(h){return this.id(h)},this)}this.refresh();this.callEvent("onaftersort",e)}},filter:function(a,b){if(this.P){this.order=this.P;delete this.P}if(a){var c=a;if(typeof a=="string"){a=dhx.Template(a);c=function(e,f){return a(e).toLowerCase().indexOf(f)!=-1}}b=(b||"").toString().toLowerCase();var d=dhx.toArray();this.order.each(function(e){c(this.get(e),b)&&d.push(e)},this);
this.P=this.order;this.order=d}this.refresh()},each:function(a,b){for(var c=0;c<this.order.length;c++)a.call(b||this,this.get(this.order[c]))},provideApi:function(a,b){b&&this.mapEvent({onbeforesort:a,onaftersort:a,onbeforeadd:a,onafteradd:a,onbeforedelete:a,onafterdelete:a,onbeforeupdate:a});for(var c=["sort","add","remove","exists","idByIndex","indexById","get","set","refresh","dataCount","filter","next","previous","clearAll","first","last"],d=0;d<c.length;d++)a[c[d]]=dhx.methodPush(this,c[d])}};
dhx.sort={create:function(a){return dhx.sort.dir(a.dir,dhx.sort.by(a.by,a.as))},as:{"int":function(a,b){a*=1;b*=1;return a>b?1:a<b?-1:0},string_strict:function(a,b){a=a.toString();b=b.toString();return a>b?1:a<b?-1:0},string:function(a,b){a=a.toString().toLowerCase();b=b.toString().toLowerCase();return a>b?1:a<b?-1:0}},by:function(a,b){if(typeof b!="function")b=dhx.sort.as[b||"string"];a=dhx.Template(a);return function(c,d){return b(a(c),a(d))}},dir:function(a,b){if(a=="asc")return b;return function(c,
d){return b(c,d)*-1}}};
dhx.RenderStack={h:function(){this.C=document.createElement("DIV");this.type=dhx.copy(this.types?this.types[this.type.name]:this.type)},customize:function(a){dhx.Type(this,a)},type_setter:function(a){if(this.types[a]){this.type=dhx.copy(this.types[a]);if(this.type.css)this.c.className+=" "+this.type.css}else this.customize(a);return a},template_setter:function(a){this.type.template=dhx.Template(a)},ca:function(a){this.callEvent("onItemRender",[a]);return this.type.template_start(a,this.type)+(a.$template?
this.type["template_"+a.$template]:this.type.template)(a,this.type)+this.type.template_end(a,this.type)},cb:function(a){this.C.innerHTML=this.ca(a);return this.C.firstChild},o:function(a){if(this.u)return this.u[a];this.u={};for(var b=this.j.childNodes,c=0;c<b.length;c++){var d=b[c].getAttribute(this.r);if(d)this.u[d]=b[c]}return this.o(a)},locate:function(a){return dhx.html.locate(a,this.r)},show:function(a){if(a=this.o(a))this.j.scrollTop=a.offsetTop-this.j.offsetTop},render:function(a,b,c){if(a){var d=
this.o(a);switch(c){case "update":if(!d)return;b=this.u[a]=this.cb(b);dhx.html.insertBefore(b,d);dhx.html.remove(d);break;case "delete":if(!d)return;dhx.html.remove(d);delete this.u[a];break;case "add":b=this.u[a]=this.cb(b);dhx.html.insertBefore(b,this.o(this.data.next(a)),this.j);break;case "move":this.render(a,b,"delete");this.render(a,b,"add");break;default:break}}else if(this.callEvent("onBeforeRender",[this.data])){this.j.innerHTML=this.data.getRange().map(this.ca,this).join("");this.u=null;
this.callEvent("onAfterRender",[])}}};
dhx.VirtualRenderStack={h:function(){this.u={};this.j.style.overflowY="scroll";dhx.event(this.j,"scroll",dhx.bind(this.Fb,this));dhx.event(window,"resize",dhx.bind(function(){this.render()},this));this.oa=[];this.attachEvent("onItemRender",function(a){a.$template=="loading"&&this.oa.push(this.data.id(a))})},o:function(a){return this.u[a]},show:function(a){range=this.kb();a=this.data.indexById(a);a=Math.floor(a/range.Pa)*range.La;this.j.scrollTop=a},render:function(a,b,c){if(a){var d=this.o(a);switch(c){case "update":if(!d)return;
a=this.u[a]=this.cb(b);dhx.html.insertBefore(a,d);dhx.html.remove(d);break;default:this.Mc();break}}else if(this.callEvent("onBeforeRender",[this.data])){this.u={};this.Fb(null,true);this.Wb=false;this.callEvent("onAfterRender",[])}},Mc:function(){if(!this.Wb){this.Wb=true;window.setTimeout(dhx.bind(function(){this.render()},this),1)}},Oa:function(a){var b=document.createElement("DIV");b.style.cssText="height:"+a+"px; width:100%; overflow:hidden;";return b},Fb:function(a,b){this.oa=[];var c=this.kb();
if(!this.j.firstChild||b){this.j.innerHTML="";this.j.appendChild(this.Oa(c.xc));this.X=[this.j.firstChild]}for(a=c.V;a<=c.Y;){for(;this.X[a]&&this.X[a].lc&&a<=c.Y;)a++;if(a>c.Y)break;for(var d=a;!this.X[d];)d--;var e=this.X[d],f=a*c.Pa+(this.data.min||0);if(f>(this.data.max||Infinity))break;var g=Math.min(f+c.Pa-1,this.data.max||Infinity),h=this.Oa(c.La),i=this.data.getIndexRange(f,g);if(!i.length)break;h.innerHTML=i.map(this.ca,this).join("");for(var j=0;j<i.length;j++)this.u[this.data.idByIndex(f+
j)]=h.childNodes[j];f=parseInt(e.style.height,10);var l=(a-d)*c.La,k=f-l-c.La;dhx.html.insertBefore(h,l?e.nextSibling:e,this.j);this.X[a]=h;h.lc=true;if(l<=0&&k>0){e.style.height=k+"px";this.X[a+1]=e}else{if(l<0)dhx.html.remove(e);else e.style.height=l+"px";if(k>0){var n=this.X[a+1]=this.Oa(k);dhx.html.insertBefore(n,h.nextSibling,this.j)}}a++}if(this.oa.length){a=this.indexById(this.oa[0]);h=this.indexById(this.oa.pop())+1;if(h>a){if(!this.callEvent("onDataRequest",[a,h-a]))return false;this.data.feed.call(this,
a,h-a)}}},kb:function(){var a=this.j.scrollTop,b=Math.max(this.j.scrollWidth,this.j.offsetWidth)-18,c=this.j.offsetHeight,d=this.qc();b=Math.floor(b/d.x)||1;var e=Math.floor(a/d.y);c=Math.ceil((c+a)/d.y)-1;var f=this.data.max?this.data.max-this.data.min:this.data.dataCount(),g=Math.ceil(f/b)*d.y;return{V:e,Y:c,ed:a,xc:g,La:d.y,Pa:b}}};
dhx.ui.map.grid=dhx.ui.grid=dhx.proto({h:function(){this.name="DataGrid";this.version="3.0";this.c.innerHTML="<div class='dhx_grid_header' style='width:100%;'></div><div class='dhx_grid_body'></div>";this.c.className+=" dhx_grid";this.W=this.c.childNodes[0];this.j=this.B=this.c.childNodes[1];dhx.extend(this,dhx.Scrollable);this.G.push(this.ac);this.data.provideApi(this,true);this.bd={};var a=this;this.data.attachEvent("onStoreUpdated",function(){dhx.delay(a.Lc,a,arguments,1)});this.Ja=null},ac:function(){},
header_setter:function(a){this.Rc(a);return a},Rc:function(a){if(!arguments.length)a=this.a.header;this.W.style.display=a?"":"none"},defaults:{select:true,type:"default",sorting:true,header:true,scroll:true},r:"dhx_f_id",on_click:{dhx_grid_row:function(a,b){if(this.a.select)this.a.select=="multiselect"?this.select(b,a.ctrlKey,a.shiftKey):this.select(b)},dhx_grid_header:function(a,b){if(this.a.sorting){b=dhx.html.locate(a,"column_id");if(b!==null){this.Ja=b;this.Db();a=this.a.fields[b].sort;this.sort(a.by,
a.dir,a.as)}}}},on_dblclick:{},on_mouse_move:{},Lc:function(){if(this.a.header){dhx.event(this.B,"scroll",dhx.bind(this.Pc,this));this.B.style.height=this.c.offsetHeight-this.W.offsetHeight-2+"px";this.j.style.width=this.W.firstChild.offsetWidth-(this.kc?20:0)+"px"}else{var a=this.a.fields,b=0;for(var c in a)b+=a[c].width;this.B.style.height=this.c.offsetHeight-2+"px";this.j.style.width=b+"px"}this.render()},fields_setter:function(a){for(var b={},c=0;c<a.length;c++){if(typeof d=="undefied")a[c].id=
dhx.uid();var d=a[c].id;this.Aa(a[c],{width:100,label:d,template:"#"+a[c].id+"#",css:this.type.css,sort:{by:"#"+d+"#",dir:"desc",as:"string"},align:"left"});a[c].template=dhx.Template(a[c].template);b[d]=a[c]}return this.type.fields=b},Db:function(){var a,b,c,d,e=this.a.fields;b=this.W;b.innerHTML="";a=dhx.html.create("table",{style:"width:0px;height:100%",cellSpacing:0,cellPadding:0,layout:"fixed"},"");b.appendChild(a);a.appendChild(document.createElement("tbody"));if(a.firstChild){c=document.createElement("tr");
a.firstChild.appendChild(c)}for(var f in e)this.Eb(c,e[f].label,e[f].width,f);if(this.a.height!="auto"){this.kc=true;d=a.offsetWidth+20<b.offsetWidth?b.offsetWidth-a.offsetWidth:20;this.Eb(c,"&nbsp;",d)}},Eb:function(a,b,c,d){var e=dhx.html.create("td",{"class":"dhx_grid_header_td",style:"width:"+c+"px;padding:0px",column_id:d},""),f=dhx.html.create("div",{"class":"dhx_div"},b===""?"&nbsp;":b);e.appendChild(f);this.W.firstChild.style.width=this.W.firstChild.offsetWidth+c+"px";a.appendChild(e);if(this.a.sorting&&
d&&d==this.Ja){a=this.a.fields[this.Ja].sort.dir;var g=dhx.html.create("div",{"class":"sort_img "+a,style:"display:inline;top:0px;left:"+(c-this.type.sort_img_width)+"px"},"");this.a.fields[this.Ja].sort.dir=a=="desc"?"asc":"desc";f.appendChild(g)}},Pc:function(){this.W.scrollLeft=this.B.scrollLeft},g:function(a,b){if(dhx.ui.map.view.prototype.g.apply(this,arguments)){a=this.O;b=this.N;this.B.style.height=b-(this.a.header?this.W.offsetHeight:0)+"px"}this.a.header&&this.Db()},qc:function(){var a=this.type,
b=a.border;return{x:this.j.offsetWidth,y:a.height+b}},type:{correction:12,template:function(a,b){var c="";for(var d in b.fields){var e=b.fields[d];c+="<td style='width:"+e.width+"px;' class='dhx_td' ><div align='"+e.align+"' style='height:"+b.height+"px;line-height:"+b.height+"px' class='dhx_cell "+e.css+"'>"+e.template(a)+"</div></td>"}return c},border:1,align:"left",height:42,css:"",sort_img_width:20,type:"text",template_start:dhx.Template("<table dhx_f_id='#id#' class='dhx_grid_row{obj.$selected?_selected:}' cellpadding='0' cellspacing='0'><tr>"),
template_end:dhx.Template("</tr></table>")}},dhx.SelectionModel,dhx.MouseEvents,dhx.KeyEvents,dhx.EditAbility,dhx.RenderStack,dhx.DataLoader,dhx.ui.map.view,dhx.EventSystem,dhx.Settings);dhx.Type(dhx.ui.grid,{name:"dummy"});
dhx.ui.map.video=dhx.ui.video_view=dhx.proto({h:function(a){if(!a.id)a.id=dhx.uid();this.name="Video";this.version="3.0";this.G.push(this.sc)},sc:function(){var a=this.a;this.c=dhx.html.create("video",{"class":"dhx_view_video",style:"width:100%;height:100%;",src:a.src},"");if(a.controls)this.c.controls=true;if(a.autoplay)this.c.autoplay=true;this.b.appendChild(this.c)},getVideo:function(){return this.c},defaults:{src:"",controls:true,autoplay:false}},dhx.ui.map.view);
dhx.ui.map.map=dhx.ui.map_view=dhx.proto({h:function(a){if(!a.id)a.id=dhx.uid();this.b.innerHTML="<div class='dhx_map_content' style='width:100%;height:100%'></div>";this.c=this.b.firstChild;this.name="Map";this.version="3.0";this.map=null;this.G.push(this.rc)},rc:function(){var a=this.a,b={zoom:a.zoom,center:a.center,mapTypeId:a.mapType};this.map=new google.maps.Map(this.c,b)},center_setter:function(a){if(typeof a!="object")a={};this.Aa(a,{x:48.724,y:8.215});return new google.maps.LatLng(a.x,a.y)},
mapType_setter:function(a){return google.maps.MapTypeId[a]},defaults:{zoom:5,center:{},mapType:"ROADMAP"}},dhx.ui.map.view);
dhx.Values={setValues:function(a){this.data.each(function(b){b.form=this.a.id;if(dhx.ui.passive[b.type].set_value)dhx.ui.passive[b.type].set_value(this.o(b.id),a[b.name]||"",a,b)},this)},getValues:function(){var a={};this.data.each(function(b){b.form=this.a.id;if(dhx.ui.passive[b.type].get_value)a[b.name]=dhx.ui.passive[b.type].get_value(this.o(b.id),a,b)},this);return a},clear:function(){var a={};this.data.each(function(b){a[b.name]=b.value||""});this.setValues(a)}};
dhx.ui.proto=dhx.proto({h:function(){this.data.provideApi(this,true);this.j=this.c;this.data.attachEvent("onStoreUpdated",dhx.bind(function(){this.render.apply(this,arguments)},this))},g:function(){dhx.ui.map.view.prototype.g.apply(this,arguments)&&this.render()}},dhx.RenderStack,dhx.DataLoader,dhx.ui.map.view,dhx.EventSystem,dhx.Settings);
dhx.ui.passive={common:{render_input:function(a,b,c,d){var e=a.label?a.labelWidth||80:0,f=258-e,g=a.align||"left",h=a.labelAlign||"left",i="<div class='dhx_inp_text_border'>";i+="<div class='dhx_inp_text_label' style='width: "+e+"px; text-align: "+h+";'>"+(a.label||"")+"</div>";i+=d?"<div class='dhx_inp_"+b+"' style='width: "+f+"px; text-align: "+g+";' >"+(a.text||a.value||"")+"</div>":"<input type='text' value='"+(a.text||a.value||"")+"' "+(c?"readonly='true'":"")+" class='dhx_inp_"+b+"' style='width: "+
f+"px; text-align: "+g+";' />";i+="</div>";return i},render_label:function(a,b){if(!a.label)return"";var c=a.labelWidth||80,d=a.labelAlign||"center";return"<div class='dhx_inp_"+b+"_label' style='width: "+c+"px; text-align: "+d+";'>"+a.label+"</div>"},escape:function(a){return(new String(a)).replace("'","&#8217;")}},text:{render:dhx.Template(function(a){return dhx.ui.passive.common.render_input(a,"text")}),get_input:function(a){return a.getElementsByTagName("input")[0]},set_value:function(a,b){var c=
this.get_input(a);c.value=b},get_value:function(a){a=this.get_input(a);return a.value}},list:{Ha:dhx.Template(function(a){return dhx.ui.passive.common.render_input(a,"list",true,true)}),render:function(a){a.popup?this.bb(a.popup,a):this.create_popup("list",a);return this.Ha(a)},after_render:function(a,b){this.set_value(a,b.value,{},b);var c=$$(b.popup.toString().split(",")[0]),d=c.l,e=this;d.attachEvent("onXLE",function(){e.set_value(a,b.value,{},b)})},create_popup:function(a,b){var c=dhx.extend({},
b);delete c.type;c.view=a;c.id=b.name+"_"+a;a=dhx.uid();var d={id:a,view:"popup",body:c};dhx.ui(d).hide();b.popup=a+","+(b.align||"bottom");this.bb(a,b)},bb:function(a){var b=this,c=$$(a.toString().split(",")[0]),d=c.l;d.attachEvent("onItemClick",function(e){c.hide();var f=$$(this.a.form),g=this.a.objId;f.get(g).value=e;f.get(g).text=this.type.template(this.get(e));b.set_value(f.o(g),e,{},f.get(g))})},get_input:function(a){return a.childNodes[0].childNodes[1]},set_value:function(a,b,c,d){c=$$(d.form);
var e=d.popup.split(",")[0],f=$$(e).l;f=f.type?f.type.template(f.get(b)||b):b;c.get(d.id).value=b;c.get(d.id).text=f;if(d.type=="combo")this.get_input(a).value=f;else this.get_input(a).innerHTML=f},get_value:function(a,b,c){return c.value}},combo:{Ha:dhx.Template(function(a){return dhx.ui.passive.common.render_input(a,"combo")}),render:function(a){a.popup?dhx.ui.passive.list.bb(a.popup,a):dhx.ui.passive.list.create_popup("list",a);return this.Ha(a)},after_render:function(a,b){this.set_value(a,b.value,
{},b);dhx.event(a,"keydown",function(c){c=c||event;var d=c.target||c.srcElement;c=b.popup.split(",");var e=$$(c[0]);window.clearTimeout(e.key_timer);e.key_timer=window.setTimeout(function(){e.l.filter(function(f){if(f.value.indexOf(d.value)===0)return true;return false})},200);e.show(d,c[1],true)},this)},set_value:function(a,b,c,d){dhx.ui.passive.list.set_value(a,b,c,d)},get_value:function(a,b,c){dhx.ui.passive.list.get_value(a,b,c)}},calendar:{render:function(a){a.popup||dhx.ui.passive.list.create_popup("calendar",
a);return dhx.ui.passive.list.Ha(a)},after_render:function(a,b){if(b.popup){this.set_value(a,b.value||"",{},b);var c=this,d=$$(b.popup.toString().split(",")[0]);d.l.attachEvent("onDateSelected",function(e){c.set_value(a,e,{},b);d.hide()})}},set_value:function(a,b,c,d){c=$$(d.popup.toString().split(",")[0]);var e=c.l;if(typeof b=="object")b=dhx.Date.dateToStr(d.date_format||e.a.calendar_date_format)(b);c=$$(d.form);var f=d.template?dhx.Template(d.template)({value:b}):b;c.get(d.id).value=b;e.selectDate(b);
c.get(d.id).text=f;dhx.ui.passive.list.get_input(a).innerHTML=f},get_value:function(a,b,c){return c.value}},counter:{render:function(a){var b=a.value||0,c=a.width||20,d=dhx.ui.passive.common.render_label(a,"counter"),e="<input type='button' class='dhx_inp_counter_prev' value='' />";e+="<div class='dhx_inp_counter_value' style='width: "+c+";'>"+b+"</div>";e+="<input type='button' class='dhx_inp_counter_next' value='' />";return a.position!="label-left"?e+d:d+e},get_input:function(a){return a.getElementsByTagName("input")[0].nextSibling},
set_value:function(a,b){this.get_input(a).innerHTML=b},get_value:function(a){return this.get_input(a).innerHTML*1},next:function(a,b,c,d){b=b||1;this.Lb(a,b,c,d)},prev:function(a,b,c,d){b=-1*(b||1);this.Lb(a,b,c,d)},Lb:function(a,b,c,d){c=typeof c=="undefined"?-Infinity:c;d=typeof d=="undefined"?Infinity:d;var e=this.get_value(a)+b;e>=c&&e<=d&&this.set_value(a,e)}},form_button:{render:dhx.Template(function(a){return"<input type='button' class='dhx_inp_form_button' style='"+(a.align!="center"?"float:"+
a.align+";":"")+"text-align: "+a.inputAlign+"; width: "+a.width+"px' value='"+a.value+"' label='"+a.value+"' />"}),set_value_:function(a,b){a.childNodes[0].value=b},get_value_:function(a){return a.childNodes[0].value}},toggle:{render:function(a){var b=a.width||"auto",c=a.widths||[b,b];if(!a.values)a.values=a.options;b=dhx.ui.passive.common.render_label(a,"toggle");var d="<input type='button' style='width: "+c[0]+";' value='"+a.options[0]+"' />";d+="<input type='button' style='width: "+c[1]+";' value='"+
a.options[1]+"'  />";return a.position!="label-left"?b+d:d+b},after_render:function(a,b){this.on(a,b.value,b.values)},get_input:function(a){return a.getElementsByTagName("input")},on:function(a,b,c){var d=this.get_input(a);if(b==c[1]){d[0].className="dhx_inp_toggle_left_off";d[1].className="dhx_inp_toggle_right_on"}else{d[0].className="dhx_inp_toggle_left_on";d[1].className="dhx_inp_toggle_right_off"}},set_value:function(a,b,c,d){this.on(a,b,d.values)},get_value:function(a,b,c){a=this.get_input(a);
c=c.values;return a[0].className=="dhx_inp_toggle_left_on"?c[0]:c[1]}},checkbox:{render:function(a){var b=a.value?"dhx_inp_checkbox_on":"dhx_inp_checkbox_on hidden",c="<div class='dhx_inp_checkbox_border'><input type='button' class='"+b+"' value='' /></div>",d=dhx.ui.passive.common.render_label(a,"checkbox");return a.position=="label-left"?d+c:c+d},get_input:function(a){return a.getElementsByTagName("input")[0]},check:function(a){var b=this.get_input(a);b.className=this.get_value(a)?"dhx_inp_checkbox_on hidden":
"dhx_inp_checkbox_on"},set_value:function(a,b){this.get_value(a)!=b&&this.check(a)},get_value:function(a){return this.get_input(a).className=="dhx_inp_checkbox_on"?1:0}},radio:{type:"radio",render:function(a){for(var b=[],c=0;c<a.data.length;c++){var d="<div dhx_radio_id='"+(a.data[c].id||dhx.uid())+"' radio_id='"+a.data[c].value+"' class='dhx_inp_radio_border'><input type='button' class='"+(a.data[c].value==a.value?"dhx_inp_radio_on":"dhx_inp_radio_on hidden")+"' value='' /></div>";a.label=a.data[c].label;
var e=dhx.ui.passive.common.render_label(a,"radio");a.position=="label-left"?b.push(e+d):b.push(d+e)}return"<div>"+b.join("</div><div>")+"</div>"},get_input:function(a){return a.getElementsByTagName("input")},check:function(a,b,c){a=this.get_input(a);for(var d=0;d<a.length;d++)a[d].className=a[d].parentNode.getAttribute("radio_id")==b&&c?"dhx_inp_radio_on":"dhx_inp_radio_on hidden"},set_value:function(a,b){this.check(a,b,true)},get_value:function(a){a=this.get_input(a);for(var b=0;b<a.length;b++)if(a[b].className.indexOf("hidden")==
-1)return a[b].parentNode.getAttribute("radio_id");return""}},button:{render:dhx.Template("<input type='button' value='#label#'>")},round_button:{render:dhx.Template("<input type='button' value='#label#'>")},default_button:{render:dhx.Template("<input type='button' value='#label#'>")},imagebutton:{render:dhx.Template("<span><img src='#src#'/>#label#</span>")},label:{render:dhx.Template("#label#")},select:{render:function(a){var b=a.options,c="<select";if(a.disabled)c+=" disabled='true'";c+=">";for(a=
0;a<b.length;a++)c+="<option"+(b[a].selected?" selected='true'":"")+(b[a].value?" value='"+b[a].value+"'":"")+">"+b[a].label+"</option>";c+="</select>";return c}},input:{render:function(a){for(var b="<input",c=["maxlength","value","disabled"],d=0;d<c.length;d++)if(a[c[d]])b+=" "+c[d]+"='"+a[c[d]]+"'";b+=" type='text'";b+="/>";return b}},image:{render:dhx.Template("<img src='#src#'/>")},icon:{render:function(a){return"<div class='dhx_el_icon_"+a.icon+"'></div>"}},segmented:{render:function(a){var b=
a.segment;if(!a.selected)a.selected=b[0].key;for(var c="",d=0;d<b.length;d++)c+="<div class='"+(a.selected==b[d].key?"selected ":"")+"segment_"+(d==b.length-1?"N":d)+"' button_id='"+b[d].key+"'>"+b[d].label+"</div>";return c}},tabbar:{render:function(a){var b=a.tabs,c="";if(a.unit_width)var d="width: "+a.unit_width+"px;";for(var e=0;e<b.length;e++){var f="",g=b[e].src;if(b[e].key==a.selected){f=" class='selected'";g=b[e].src_selected||b[e].src}c+="<div"+f+" button_id='"+b[e].key+"' style='"+(d||"")+
"'><img src='"+g+"'/>";c+="<span>"+b[e].label+"</span>";c+="</div>"}return c}},handlers:{mb:function(a,b){a=dhx.html.locate(a,"button_id");if(this.callEvent("onBeforeTabClick",[b,a])){this.data.get(b).selected=a;this.refresh(b);this.callEvent("onAfterTabClick",[b,a])}},dhx_el_segmented:function(a,b){dhx.ui.passive.handlers.mb.call(this,a,b)},dhx_el_tabbar:function(a,b){dhx.ui.passive.handlers.mb.call(this,a,b)},dhx_inp_counter_next:function(a){a=dhx.html.locate(a,this.r);dhx.ui.passive[this.get(a).type].next(this.o(a),
this.get(a).step,this.get(a).min,this.get(a).max)},dhx_inp_counter_prev:function(a){a=dhx.html.locate(a,this.r);dhx.ui.passive[this.get(a).type].prev(this.o(a),this.get(a).step,this.get(a).min,this.get(a).max)},dhx_inp_toggle_left_off:function(a){a=dhx.html.locate(a,this.r);var b=this.get(a).values;dhx.ui.passive[this.get(a).type].on(this.o(a),b[0],b);return true},dhx_inp_toggle_right_off:function(a){a=dhx.html.locate(a,this.r);var b=this.get(a).values;dhx.ui.passive[this.get(a).type].on(this.o(a),
b[1],b);return true},dhx_inp_list:function(a,b,c){a=dhx.html.locate(a,this.r);b=this.get(a).popup.split(",");var d=dhx.ui.get(b[0]);d.l.a.form=this.a.id;d.l.a.objId=a;d.show(c,b[1],true)},dhx_inp_combo:function(a,b,c){c.focus();dhx.ui.passive.handlers.dhx_inp_list.call(this,a,b,c)},dhx_inp_checkbox_border:function(a){a=dhx.html.locate(a,this.r);dhx.ui.passive[this.get(a).type].check(this.o(a))},dhx_inp_checkbox_label:function(a){a=dhx.html.locate(a,this.r);dhx.ui.passive[this.get(a).type].check(this.o(a))},
dhx_inp_radio_border:function(a){var b=dhx.html.locate(a,this.r);a=dhx.html.locate(a,"radio_id");dhx.ui.passive[this.get(b).type].check(this.o(b),a,true)},dhx_inp_radio_label:function(a,b,c){c=c.parentNode.getElementsByTagName("input")[0];return this.on_click.dhx_inp_radio_border.call(this,c,b,c)}}};
dhx.ui.form=dhx.ui.map.form=dhx.proto({defaults:{scroll:true},h:function(a){this.name="Form";this.c.className+=" dhx_form";a.id||this.define("id",dhx.uid());this.attachEvent("onAfterRender",function(){this.data.each(function(b){b.form=this.a.id;dhx.ui.passive[b.type].after_render&&dhx.ui.passive[b.type].after_render(this.o(b.id),b)},this)})},r:"dhx_inp_id",type:{template:function(a,b){var c=dhx.ui.passive[a.type];if(c)return c.render(a,b)},template_start:dhx.Template(function(a){var b="dhx_form_item "+
(a.sameLine?"dhx_form_float":"dhx_form_clear"),c=a.type=="radio"?"height:auto;":"";if(a.type=="checkbox")c+="width:auto;";return"<div class='"+b+"' style='"+c+"' dhx_inp_id='"+a.id+"'>"}),template_end:dhx.Template("</div>")},loadValues:function(a,b,c){this.callEvent("onXLS",[]);var d="xml";if(typeof b=="string"){d=b;b=c}dhx.ajax(a,[function(){this.parseValues(text,d);this.callEvent("onXLE",[])},b],this)},Qc:function(a){a=a||"xml";return dhx.DataDriver[a]},parseValues:function(a,b){b=this.Qc(b);a=
b.toObject(a,null);if(b.getTopElement)a=b.getTopElement(a);var c=b.getDetails(a);this.setValues(c.data||c)},g:function(){dhx.ui.map.view.prototype.g.apply(this,arguments)},on_click:dhx.ui.passive.handlers},dhx.Values,dhx.MouseEvents,dhx.Scrollable,dhx.ui.proto);dhx.animate=function(a,b){if(a instanceof Array)for(var c=0;c<a.length;c++)dhx.animate(a[c],b);else{c=dhx.toNode(a);c.Ra?dhx.animate.end(c,b):dhx.animate.start(c,b)}};
dhx.animate.end=function(a,b){a.style[dhx.env.transform_prefix.replace(/-/g,"")+"TransitionDuration"]="1ms";a.Ra=null;dhx.Vb&&window.clearTimeout(dhx.Vb);dhx.Vb=dhx.delay(dhx.animate,dhx,[a,b],10)};dhx.animate.isSupported=function(){return dhx.env.transform&&dhx.env.transition};dhx.animate.formLine=function(a,b,c){a.parentNode.style.position="relative";b.style.position="absolute";b.style.top="0px";b.style.left=(c=="left"?1:-1)*a.offsetWidth+"px";a.parentNode.appendChild(b);return[a,b]};
dhx.animate.breakLine=function(a){dhx.html.remove(a[0]);dhx.animate.clear(a[0]);dhx.animate.clear(a[1]);a[1].style.position=""};dhx.animate.clear=function(a){var b=dhx.env.transform_prefix.replace(/-/g,"");a.style[b+"Transform"]="";a.style[b+"Transition"]=""};
dhx.animate.start=function(a,b){var c=dhx.env.transform_prefix,d=c.replace(/-/g,"");if(typeof b=="string")b={type:b};var e=a.Ra=dhx.Settings.Aa(b,{type:"slide",delay:"0",duration:"500",timing:"ease",x:0,y:0});switch(e.type=="slide"&&e.direction){case "right":e.x=a.offsetWidth;break;case "left":e.x=-a.offsetWidth;break;case "top":e.y=-a.offsetHeight;break;case "bottom":e.y=a.offsetHeight;break;default:break}var f=e.duration+"ms "+e.timing+" "+e.delay+"ms",g="",h="",i="";switch(e.type){case "fade":h=
"opacity "+f;g="opacity: 0;";break;case "show":h="opacity "+f;g="opacity: 1;";break;case "slide":b=e.x+"px";var j=e.y+"px";i="translate("+b+", "+j+")";h=c+"transform "+f;break;default:break}a.style[d+"Transition"]=h;dhx.delay(function(){if(g)a.style.cssText+=g;if(i)a.style[d+"Transform"]=i;var l=dhx.event(a,d+"TransitionEnd",function(k){a.Ra=null;if(e.callback)e.callback.call(e.master||window,a,e,k);dhx.eventRemove(l)})})};
dhx.Modality={modal_setter:function(a){if(a){if(!this.$){this.$=dhx.html.create("div",{"class":a=="rich"?"dhx_modal_rich":"dhx_modal"});this.$.style.zIndex=dhx.ui.zIndex();this.b.style.zIndex=dhx.ui.zIndex();document.body.appendChild(this.$)}}else{this.$&&dhx.html.remove(this.$);this.$=null}return a}};
dhx.ui.map.window=dhx.ui.window=dhx.proto({h:function(a){this.b.innerHTML="<div class='dhx_win_content'><div class='dhx_win_head'></div><div class='dhx_win_body'></div></div>";this.c=this.b.firstChild;this.q=this.c.childNodes[0];this.B=this.c.childNodes[1];this.b.className+=" dhx_window";this.Q=this.l=null;this.a.k={top:false,left:false,right:false,bottom:false};if(!a.id)a.id=dhx.uid()},show:function(a,b,c){this.b.style.zIndex=dhx.ui.zIndex();if(a){a=dhx.toNode(a);var d=document.body.offsetWidth,
e=document.body.offsetHeight,f=a.offsetWidth,g=a.offsetHeight,h=this.ja;a=dhx.html.offset(a);var i=10,j=10,l=6;c="top";var k=0,n=0,m=0,o=0;if(b=="right"){o=a.x+i+f;j=-g;c="left";k=Math.round(a.y+g/2);n=o-l}else if(b=="left"){o=a.x-i-h[0];j=-g;c="right";k=Math.round(a.y+g/2);n=o+h[0]+1}else{o=d-a.x>h[0]?a.x:d-i-h[0];n=Math.round(a.x+f/2)}if(e-g-a.y-j>h[1]){m=g+a.y+j;if(!k){c="top";k=m-l}}else{m=a.y-j-h[1];if(m<0){m=0;c=false}else if(!k){c="bottom";k=m+h[1]+1}}this.setPosition(o,m);c&&this.Gb&&this.Gb(c,
n,k)}this.Uc=new Date;this.b.style.display="block";this.callEvent("onShow",[])},hide:function(){if(!(new Date-this.Uc<100)){this.a.modal&&this.define("modal",false);this.a.position=="top"?dhx.animate(this.b,{type:"slide",x:0,y:0,duration:300,callback:this.pb,master:this}):this.pb()}},pb:function(){this.b.style.display="none";this.callEvent("onHide",[])},close:function(){this.define("modal",false);dhx.html.remove(this.b);this.destructor()},body_setter:function(a){if(typeof a!="object")a={template:a};
this.l=dhx.ui.pa(a);this.l.la=this;this.B.appendChild(this.l.b);return a},head_setter:function(a){if(a===false)return a;if(typeof a!="object")a={template:a,css:"dhx_alert_template"};this.Q=dhx.ui.pa(a);this.Q.la=this;this.q.appendChild(this.Q.b);return a},resize:function(){var a=this.i();this.g(a[1]||this.a.width,a[3]||this.a.height);this.Sc(this.a.left,this.a.top)},Sc:function(a,b){if(this.a.position){a=Math.round((document.body.offsetWidth-this.a.width)/2);b=Math.round((document.body.offsetHeight-
this.a.height)/2);if(this.a.position=="top")b=dhx.animate.isSupported()?-1*this.a.height:10;this.setPosition(a,b);this.a.position=="top"&&dhx.animate(this.b,{type:"slide",x:0,y:this.a.height,duration:300})}else this.setPosition(a,b)},setPosition:function(a,b){this.b.style.top=b+"px";this.b.style.left=a+"px";this.a.left=a;this.a.top=b},i:function(){var a=this.l.i();if(this.Q){var b=this.Q.i();if(b[3])this.a.head_height=b[3]}if(a[3]){a[3]+=this.a.head!==false?this.a.head_height:0;this.a.height=a[3]}if(a[1])this.a.width=
a[1];if(a[0]||a[2])this.a.gravity=Math.max(a[0],a[2]);return dhx.ui.map.view.prototype.i.call(this)},g:function(a,b){if(dhx.ui.map.view.prototype.g.call(this,a,b)){a=this.O;b=this.N;if(this.a.head===false){this.q.style.display="none";this.l.g(a,b)}else{this.Q.g(a,this.a.head_height);this.l.g(a,b-this.a.head_height)}}},defaults:{head_height:43,width:300,height:200,top:100,left:100}},dhx.ui.map.view,dhx.Movable,dhx.Modality,dhx.EventSystem);
dhx.ui.popup=dhx.ui.map.popup=dhx.proto({h:function(){this.a.head=false;this.c.onclick=dhx.html.stopEvent;dhx.attachEvent("onClick",dhx.bind(this.hide,this));this.attachEvent("onHide",this.qb)},i:function(){var a=this.l.i();if(a[3])this.a.height=a[3]+this.a.padding*2;if(a[1])this.a.width=a[1]+this.a.padding*2;if(a[0]||a[2])this.a.gravity=Math.max(a[0],a[2]);return dhx.ui.map.view.prototype.i.call(this)},g:function(a,b){if(dhx.ui.map.view.prototype.g.call(this,a,b)){a=this.O-this.a.padding*2;b=this.N-
this.a.padding*2;this.c.style.padding=this.a.padding+"px";this.q.style.display="none";this.l.g(a,b)}},body_setter:function(a){a=dhx.ui.map.window.prototype.body_setter.call(this,a);this.l.a.k={top:false,left:false,right:false,bottom:false};return a},defaults:{padding:8},head_setter:null,Gb:function(a,b,c){this.qb();document.body.appendChild(this.na=dhx.html.create("DIV",{"class":"dhx_point_"+a},""));this.na.style.zIndex=dhx.ui.zIndex();this.na.style.top=c+"px";this.na.style.left=b+"px"},qb:function(){this.na=
dhx.html.remove(this.na)}},dhx.ui.window);dhx.event(window,"click",function(a){dhx.callEvent("onClick",[a||event])});
dhx.ui.alert=dhx.proto({defaults:{position:"center",head:{template:"Info",css:"dhx_alert_template"},height:170,modal:true,callback:null,body:{type:"clean",rows:[{template:"<div class='dhx_alert_text'>#text#</div>",data:{text:"You have forgot to define the text :) "}},{id:"dhx_alert_controls",view:"toolbar",type:"BigBarV",height:60,data:[{type:"button",label:"Ok",click:function(){this.getParent().getParent().Na(true)}}]}]}},h:function(a){a.container=document.body;this.G.push(this.resize)},Bb:function(a){if(typeof a==
"string")a={title:this.defaults.head.template,message:a};dhx.extend(a,this.defaults);delete a.head;delete a.body;this.ma(a,{});this.show()},title_setter:function(a){this.Q.define("template",a);this.Q.render()},message_setter:function(a){var b=this.l.d[0];b.data={text:a};b.render()},Na:function(a){this.hide();this.a.callback&&dhx.toFunctor(this.a.callback).call(this,a)}},dhx.ui.window);dhx.alert=dhx.single(dhx.ui.alert);
dhx.ui.confirm=dhx.proto({defaults:{height:210,body:{type:"clean",rows:[{id:"dhx_confirm_message",template:"<div class='dhx_alert_text'>#text#</div>",data:{text:"You have forgot to define the text :) "}},{id:"dhx_confirm_controls",view:"toolbar",type:"BigBarV",height:110,data:[{type:"button",label:"Ok",click:function(){this.getParent().getParent().Na(true)}},{type:"default_button",label:"Cancel",click:function(){this.getParent().getParent().Na(false)}}]}]}}},dhx.ui.alert);dhx.confirm=dhx.single(dhx.ui.confirm);
dhx.ui.map.tabbar=dhx.ui.tabbar=dhx.proto({defaults:{animate:{}},h:function(){this.I=0;this.F=1},H:function(a){a=a||this.T;for(var b=0;b<a.length;b++)a[b].k=this.a.k||{top:1,bottom:1,left:1,right:1};dhx.ui.layout.prototype.H.call(this,a);for(b=1;b<this.d.length;b++)dhx.html.remove(this.d[b].b);for(b=0;b<a.length;b++){var c=this.d[b];if(!c.d){var d=c.a.k;if(d.top)c.b.style.borderTopWidth="0px";if(d.left)c.b.style.borderLeftWidth="0px";if(d.right)c.b.style.borderRightWidth="0px";if(d.bottom)c.b.style.borderBottomWidth=
"0px"}}},cells_setter:function(a){this.T=a},Ib:function(a){if(this.rb)return dhx.delay(this.Ib,this,[a]);for(var b=-1,c=0;c<this.d.length;c++)if(this.d[c]==a){b=c;break}if(!(b<0||b==this.I))if(dhx.animate.isSupported()&&this.a.animate){var d=this.a.animate;d.direction=b<this.I?"right":"left";var e=dhx.animate.formLine(this.d[this.I].b,this.d[b].b,d.direction);this.d[b].i();this.d[b].g(this.O,this.N);d.callback=function(){dhx.animate.breakLine(e);this.I=b;this.rb=false;d.master=d.callback=null};d.master=
this;dhx.animate(e,d);this.rb=true}else{dhx.html.remove(this.d[this.I].b);this.I=b;this.b.appendChild(this.d[c].b);this.d[this.I].i();this.d[this.I].g(this.O,this.N)}},i:function(){var a=this.d[this.I].i();if(this.a.height>-1){a[3]=this.a.height;a[2]=0}if(this.a.width>-1){a[1]=this.a.width;a[0]=0}if(a[0])a[1]=0;if(a[2])a[3]=0;return a},g:function(a,b){dhx.ui.view.prototype.g.call(this,a,b);this.d[this.I].g(a,b)}},dhx.ui.map.layout);
dhx.ui.map.list=dhx.ui.list=dhx.proto({h:function(){this.name="List";this.data.provideApi(this,true);this.data.attachEvent("onStoreUpdated",dhx.bind(this.render,this))},defaults:{select:false,scroll:true},r:"dhx_l_id",on_click:{dhx_list_item:function(a,b){if(this.a.select)this.a.select=="multiselect"?this.select(b,a.ctrlKey,a.shiftKey):this.select(b)}},i:function(){if(this.type.width!="auto")this.a.width=this.type.width+(this.type.padding+this.type.margin)*2;if(this.a.y_count)this.a.height=(this.type.height+
(this.type.padding+this.type.margin)*2)*this.a.y_count;return dhx.ui.map.view.prototype.i.call(this)},type:{css:"",template:dhx.Template("#value#"),width:300,height:22,margin:0,padding:10,border:1,template_start:dhx.Template("<div dhx_l_id='#id#' class='dhx_list_item dhx_list_{common.css}_item{obj.$selected?_selected:}' style='width:{common.width}px; height:{common.height}px; padding:{common.padding}px; margin:{common.margin}px; overflow:hidden;'>"),template_end:dhx.Template("</div>")}},dhx.MouseEvents,
dhx.SelectionModel,dhx.Scrollable,dhx.ui.proto);
dhx.Type(dhx.ui.list,{name:"GroupList",template:function(a,b){if(a.item)return b.template_group(a,b);return b.template_item(a,b)},css:"group",template_start:"<div dhx_l_id='#id#' class='dhx_list_item dhx_list{obj.item?_group:_item}{obj.$template?_back:}{obj.$selected?_selected:}' style='width:{common.width}px; height:{common.height}px; padding:{common.padding}px; margin:{common.margin}px; overflow:hidden;'>",template_back:"&lt; #value#",template_item:"#value#",template_group:"#value#"});
dhx.ui.map.grouplist=dhx.ui.grouplist=dhx.proto({h:function(){this.data.Ub=true;this.type=this.types.GroupList;this.Ea=new dhx.DataStore;this.Da=this.data.order;this.R=[];this.Ea.pull=this.data.pull},on_click:{dhx_list_item:function(a,b){for(var c=0;c<this.R.length;c++)if(this.R[c]==b){for(a=c;a<this.R.length;a++)this.data.get(this.R[a]).$template="";if(c){this.Da=this.data.get(this.R[c-1]).item;this.R.splice(c)}else{this.Da=this.data.order;this.R=[]}return this.render()}c=this.get(b);if(c.item){this.R.push(b);
c.$template="back";this.Da=c.item;return this.render()}else if(this.a.select)this.a.select=="multiselect"?this.select(b,a.ctrlKey,a.shiftKey):this.select(b)}},render:function(a){if(!(a&&!this.Ea.get(a))){this.Ea.order=[].concat(this.R).concat(this.Da);var b=this.data;this.data=this.Ea;dhx.RenderStack.render.apply(this,arguments);this.data=b}}},dhx.ui.list);
dhx.ui.map.aitem=dhx.ui.aitem=dhx.proto({h:function(a){if(!a.id)a.id=dhx.uid();this.b.innerHTML="<div dhx_ai_id='"+a.id+"'  class='dhx_aitem_header'><div class='dhx_aitem_button' ></div><div class='dhx_aitem_label' ></div></div><div class='dhx_aitem_body'></div>";this.c=this.b;this.q=this.c.childNodes[0];if(!a.header)this.q.style.display="none";this.ob=this.c.childNodes[0].childNodes[1];this.nb=this.c.childNodes[0].childNodes[0];this.B=this.c.childNodes[1];this.b.className+=" dhx_aitem";this.Q=this.l=
null;this.d=true;this.a.k=a.k||{top:1,bottom:1,left:1,right:1};this.G.push(this.dc)},dc:function(){var a=this.a.k;if(a){this.ua(a.top,"borderTopWidth");this.ua(a.left,"borderLeftWidth");this.ua(a.right,"borderRightWidth");this.ua(a.bottom,"borderBottomWidth")}},ua:function(a,b){if(a){this.q.style[b]="0px";this.l.d||(this.l.b.style[b]="0px")}},r:"dhx_ai_id",body_setter:function(a){if(typeof a!="object")a={template:a};a.k=dhx.copy(this.a.k);this.l=dhx.ui.pa(a);this.B.appendChild(this.l.b);return a},
header_setter:function(a){if(a)a=dhx.Template(a);return a},header_alt_setter:function(a){if(a)a=dhx.Template(a);return a},i:function(){var a=this.l.i(),b=0;if(this.getParent().F)if(this.a.collapse){a[3]=this.wa();a[2]=0}else b=this.a.header_height;else if(this.a.collapse){a[1]=this.wa();a[0]=0}this.a.width=a[1]||-1;this.a.height=a[3]?a[3]+b:-1;if(a[0]||a[2])this.a.gravity=Math.max(a[0],a[2]);return dhx.ui.view.prototype.i.call(this)},on_click:{dhx_aitem_header:function(a){this.Qb(a)},dhx_aitem_header_v:function(a){this.Qb(a)}},
Qb:function(a){this.define("collapse",!this.a.collapse);dhx.callEvent("onClick",[]);return dhx.html.preventEvent(a)},collapse_setter:function(a){if(this.a.header!==false){if(this.a.collapse)this.jc();else if(this.getParent().ec(this))this.hc();else return false;(this.a.collapse=a)||this.getParent().$b(this);this.refresh();this.getParent().Nc();return a}},collapse:function(){this.define("collapse",true)},expand:function(){this.define("expand",true)},jc:function(){this.B.style.display="";dhx.html.removeCss(this.nb,
"collapsed")},hc:function(){this.getParent();if(this.a.header_alt)this.ob.innerHTML=this.a.header_alt();this.B.style.display="none";dhx.html.addCss(this.nb,"collapsed")},refresh:function(){var a=this.a[this.a.collapse?"header_alt":"header"]||this.a.header;if(a)this.ob.innerHTML=a()},wa:function(){return this.a.collapse?this.a.header_alt_height:this.a.header_height},g:function(a,b){if(dhx.ui.view.prototype.g.call(this,a,b)){a=this.O;b=this.N;var c=this.wa()-(this.a.k.top?0:1);if(this.a.header){this.q.style.height=
c+"px";this.q.style.lineHeight=c+"px";this.q.style.width="auto";this.q.style[dhx.env.transform_prefix.replace(/-/g,"")+"Transform"]="";if(this.a.k.left)this.q.style.borderLeftWidth="0px";if(this.a.k.right)this.q.style.borderRightWidth="0px";if(this.getParent().F||!this.a.collapse)b-=this.wa();else if(this.a.collapse){this.q.style.width=b-2+"px";this.q.style.borderLeftWidth=this.q.style.borderRightWidth="1px";var d=Math.floor(-b/2+a/2);this.q.style[dhx.env.transform_prefix.replace(/-/g,"")+"Transform"]=
"rotate(-90deg) translate("+d+"px, "+d+"px)"}}this.a.collapse||this.l.g(a,b)}},defaults:{icon_size:25,header:"",header_alt:false,body:"",header_height:42,header_alt_height:42}},dhx.MouseEvents,dhx.EventSystem,dhx.ui.view);
dhx.ui.map.accordion=dhx.ui.accordion=dhx.proto({h:function(){},H:function(){for(var a=0;a<this.T.length;a++)this.T[a].view="aitem";dhx.ui.map.layout.prototype.H.call(this);for(a=0;a<this.d.length;a++)this.d[a].refresh()},$b:function(a){if(this.a.multi===false)for(var b=0;b<this.d.length;b++)a!=this.d[b]&&!this.d[b].a.collapse&&this.d[b].collapse()},ec:function(a){if(this.a.multi===true)return true;for(var b=0;b<this.d.length;b++)if(a!=this.d[b]&&!this.d[b].a.collapse)return true;return false},Nc:function(){this.i();
this.g.apply(this,this.ja)},defaults:{multi:"mixed"}},dhx.ui.map.layout);
dhx.ui.map.toolbar=dhx.ui.toolbar=dhx.proto({r:"dhx_tb_id",h:function(a){this.name="Toolbar";this.Fa={};a.id||this.define("id",dhx.uid());this.c.className+=" dhx_toolbar";this.data.attachEvent("onStoreUpdated",dhx.bind(this.Hc,this));this.attachEvent("onItemClick",this.gc);this.attachEvent("onAfterRender",function(){this.data.each(function(b){b.form=this.a.id;dhx.ui.passive[b.type].after_render&&dhx.ui.passive[b.type].after_render(this.o(b.id),b)},this)})},type:{template_start:function(a,b){var c=
"<div dhx_tb_id='"+a.id+"' class='dhx_el_"+a.type;if(a.css)c+=" "+a.css+"";if(a.disabled)c+=" disabled";c+="'";var d="style='float: left'";if(b.vertical)d="style='float:none'";else if(a.align){d="style='float:"+a.align+"'";if(a.align=="center"||a.align=="middle")d="style='display:inline-block'"}c+=" "+d;c+=">";return c},template_end:dhx.Template("</div>"),template:function(a,b){var c=dhx.ui.passive[a.type];return a.disabled&&c.render_disabled?c.render_disabled(a,b):c.render(a,b)},height:42},i:function(){if(this.type.vertical&&
this.type.width)this.a.width=this.type.width;else this.a.height=this.type.height;return dhx.ui.map.view.prototype.i.call(this)},Hc:function(){this.Fa={};this.data.each(function(a){if(a.popup)this.Fa[a.id]=a.popup},this)},gc:function(a,b,c){this.get(a).click&&dhx.toFunctor(this.get(a).click).call(this,a,b,c);if(this.Fa[a]){a=this.Fa[a].split(",");b=dhx.ui.get(a[0]);b.show(c,a[1],true)}},on_click:dhx.ui.passive.handlers},dhx.Values,dhx.MouseEvents,dhx.ui.proto);
dhx.Type(dhx.ui.toolbar,{name:"MainBar",height:43,css:"dhx_mainbar"});dhx.Type(dhx.ui.toolbar,{name:"SubBar",height:42,css:"dhx_subbar"});dhx.Type(dhx.ui.toolbar,{name:"BigBarV",css:"dhx_bigbar",vertical:true,width:300});dhx.Type(dhx.ui.toolbar,{name:"BigBar",css:"dhx_bigbar",height:55});dhx.Type(dhx.ui.toolbar,{name:"BigTabBar",css:"dhx_bigtabbar",height:49});dhx.math={};dhx.math.$c=["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"];
dhx.math.toHex=function(a,b){a=parseInt(a,10);for(str="";a>0;){str=this.$c[a%16]+str;a=Math.floor(a/16)}for(;str.length<b;)str="0"+str;return str};dhx.math.toFixed=function(a){if(a<10)return"0"+a;return a};
dhx.Date={Locale:{month_full:["January","February","March","April","May","June","July","August","September","October","November","December"],month_short:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],day_full:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],day_short:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]},datePart:function(a){a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a},timePart:function(a){return(a.valueOf()/
1E3-a.getTimezoneOffset()*60)%86400},weekStart:function(a){var b=a.getDay();if(this.config.start_on_monday)if(b===0)b=6;else b--;return this.date_part(this.add(a,-1*b,"day"))},monthStart:function(a){a.setDate(1);return this.date_part(a)},yearStart:function(a){a.setMonth(0);return this.month_start(a)},dayStart:function(a){return this.date_part(a)},add:function(a,b,c){var d=new Date(a.valueOf());switch(c){case "day":d.setDate(d.getDate()+b);break;case "week":d.setDate(d.getDate()+7*b);break;case "month":d.setMonth(d.getMonth()+
b);break;case "year":d.setYear(d.getFullYear()+b);break;case "hour":d.setHours(d.getHours()+b);break;case "minute":d.setMinutes(d.getMinutes()+b);break;default:return dhx.Date["add_"+c](a,b,c)}return d},copy:function(a){return new Date(a.valueOf())},dateToStr:function(a,b){a=a.replace(/%[a-zA-Z]/g,function(c){switch(c){case "%d":return'"+dhx.math.toFixed(date.getDate())+"';case "%m":return'"+dhx.math.toFixed((date.getMonth()+1))+"';case "%j":return'"+date.getDate()+"';case "%n":return'"+(date.getMonth()+1)+"';
case "%y":return'"+dhx.math.toFixed(date.getFullYear()%100)+"';case "%Y":return'"+date.getFullYear()+"';case "%D":return'"+dhx.Date.Locale.day_short[date.getDay()]+"';case "%l":return'"+dhx.Date.Locale.day_full[date.getDay()]+"';case "%M":return'"+dhx.Date.Locale.month_short[date.getMonth()]+"';case "%F":return'"+dhx.Date.Locale.month_full[date.getMonth()]+"';case "%h":return'"+dhx.math.toFixed((date.getHours()+11)%12+1)+"';case "%g":return'"+((date.getHours()+11)%12+1)+"';case "%G":return'"+date.getHours()+"';
case "%H":return'"+dhx.math.toFixed(date.getHours())+"';case "%i":return'"+dhx.math.toFixed(date.getMinutes())+"';case "%a":return'"+(date.getHours()>11?"pm":"am")+"';case "%A":return'"+(date.getHours()>11?"PM":"AM")+"';case "%s":return'"+dhx.math.toFixed(date.getSeconds())+"';case "%W":return'"+dhx.math.toFixed(dhx.Date.getISOWeek(date))+"';default:return c}});if(b)a=a.replace(/date\.get/g,"date.getUTC");return new Function("date",'return "'+a+'";')},strToDate:function(a,b){var c="var temp=date.split(/[^0-9a-zA-Z]+/g);",
d=a.match(/%[a-zA-Z]/g);for(a=0;a<d.length;a++)switch(d[a]){case "%j":case "%d":c+="set[2]=temp["+a+"]||1;";break;case "%n":case "%m":c+="set[1]=(temp["+a+"]||1)-1;";break;case "%y":c+="set[0]=temp["+a+"]*1+(temp["+a+"]>50?1900:2000);";break;case "%g":case "%G":case "%h":case "%H":c+="set[3]=temp["+a+"]||0;";break;case "%i":c+="set[4]=temp["+a+"]||0;";break;case "%Y":c+="set[0]=temp["+a+"]||0;";break;case "%a":case "%A":c+="set[3]=set[3]%12+((temp["+a+"]||'').toLowerCase()=='am'?0:12);";break;case "%s":c+=
"set[5]=temp["+a+"]||0;";break}a="set[0],set[1],set[2],set[3],set[4],set[5]";if(b)a=" Date.UTC("+a+")";return new Function("date","var set=[0,0,1,0,0,0]; "+c+" return new Date("+a+");")},getISOWeek:function(a){if(!a)return false;var b=a.getDay();if(b===0)b=7;var c=new Date(a.valueOf());c.setDate(a.getDate()+(4-b));var d=c.getFullYear(),e=Math.floor((c.getTime()-(new Date(d,0,1)).getTime())/864E5),f=1+Math.floor(e/7);return f},getUTCISOWeek:function(a){return this.getISOWeek(a)}};
dhx.ui.calendar=dhx.ui.map.calendar=dhx.proto({defaults:{date:new Date,start_on_monday:true,navigation:true,week_header:false,week_number:false,time_select:false,movable:false,skip_empty_weeks:true,minute_step:15,hour_start:6,hour_end:24,hour_format:"%H",calendar_date_format:"%Y-%m-%d",calendar_month_header:"%F %Y",calendar_day_header:"%d",calendar_week_header:"W#",calendar_week:"%W",width:300,height:300,cell_auto_height:false,cell_height:36,month_header_height:40,week_header_height:20,time_select_height:32,
selected_date_classname:"dhx_cal_selected_day"},h:function(){this.name="Calendar";this.G.push(this.Zb)},Zb:function(){this.z={};this.z.calendar_date=dhx.Date.dateToStr(this.a.calendar_date_format);this.z.calendar_date_obj=dhx.Date.strToDate(this.a.calendar_date_format);this.z.calendar_month=dhx.Date.dateToStr(this.a.calendar_month_header);this.z.calendar_day=dhx.Date.dateToStr(this.a.calendar_day_header);this.z.calendar_week=dhx.Date.dateToStr(this.a.calendar_week);this.cd=false;this.ib();this.Cb()},
i:function(){if(this.Yb)this.a.width=this.Yb;if(this.Y)this.a.height=this.Y;return dhx.ui.map.view.prototype.i.call(this)},g:function(a,b){dhx.ui.map.view.prototype.g.call(this,a,b)},oc:function(){var a=new Date(this.a.date);a.setDate(1);this.wb=new Date(a);var b=a.getDay();this.Xb=this.a.start_on_monday?1:0;this.Ca=(b-this.Xb+7)%7;this.Va=32-(new Date(a.getFullYear(),a.getMonth(),32)).getDate();var c=42-this.Ca-this.Va;this.yc=new Date(a.setDate(this.Va));this.dd=new Date(a.setDate(a.getDate()+c));
this.D=this.a.skip_empty_weeks?6-Math.floor(c/7):6;this.Wa=this.D*7-this.Ca-this.Va},ib:function(){this.oc();this.ea=[];this.U=[];var a=this.Yb=this.O||this.a.width;a+=1;for(var b=this.N||this.a.height,c=this.a.week_number?8:7,d=0;d<c;d++){this.U[d]=Math.ceil(a/(c-d));a-=this.U[d]}var e=this.a.month_header_height;if(this.a.week_header)e+=this.a.week_header_height;if(this.a.time_select)e+=this.a.time_select_height;if(this.a.cell_auto_height){this.Y=b;for(var f=0;f<this.D;f++){this.ea[f]=Math.ceil((b-
e)/(this.D-f));b-=this.ea[f]}}else{for(f=0;f<this.D;f++)this.ea[f]=this.a.cell_height;this.Y=e+this.D*this.a.cell_height}},selectDate:function(a){if(typeof a=="string")a=this.z.calendar_date_obj(a);if(a){var b=this.a.selected_date_classname;if(this.m){var c=this.z.calendar_date(this.m);this.da[c]&&dhx.html.removeCss(this.da[c],b)}var d=this.z.calendar_date(a);if(this.da[d]){dhx.html.addCss(this.da[d],b);this.m=a}}},showCalendar:function(a){if(typeof a=="string")a=this.z.calendar_date_obj(a);if(!a)a=
this.a.date;this.a.date=a;this.ib();var b=this.getParent();b&&b.resize();this.Cb()},Cb:function(){var a;if(this.Ma)a=this.Ma;else{a=document.createElement("div");a.className="dhx_mini_calendar"}this.Ma=a;a.setAttribute("date",this.z.calendar_date(this.a.date));a.innerHTML="<div class='dhx_cal_month'></div>";a.childNodes[0].innerHTML=this.z.calendar_month(this.a.date);if(this.a.navigation)a.childNodes[0].innerHTML+=this.zc();var b=1;if(this.a.week_header){a.innerHTML+="<div class='dhx_cal_header'></div>";
a.childNodes[b].innerHTML=this.ad();a.childNodes[b++].style.height=this.a.week_header_height+"px"}a.innerHTML+="<div class='dhx_cal_body'></div>";a.childNodes[b++].innerHTML=this.cc();if(this.a.time_select){a.innerHTML+="<div class='dhx_cal_time_select'></div>";a.childNodes[b].innerHTML=this.Zc()}this.c.appendChild(a);a=a.getElementsByTagName("table");var c=a[a.length-1].getElementsByTagName("div");this.da={};for(a=0;a<c.length;a++)this.da[c[a].getAttribute("date")]=c[a];this.m&&this.wb.valueOf()<=
this.m.valueOf()&&this.yc.valueOf()>=this.m.valueOf()&&this.selectDate(this.m)},ad:function(){var a="",b=this.a.start_on_monday?1:0,c=0,d=0;if(this.a.week_number){d=1;var e=this.a.calendar_week_header;a+="<div class='dhx_cal_week_header' style='width: "+(this.U[0]-1)+"px; left: "+c+"px;' >"+e+"</div>";c+=this.U[0]}for(e=0;e<7;e++){var f=(b+e)%7,g=dhx.Date.Locale.day_short[f],h="dhx_cal_day_name",i=this.U[e+d]-1;if(e==6){h+=" dhx_cal_day_name_last";i+=1}if(f===0)h+=" dhx_sunday";if(f==6)h+=" dhx_saturday";
a+="<div class='"+h+"' style='width: "+i+"px; left: "+c+"px;' >"+g+"</div>";c+=this.U[e+d]}return a},cc:function(){var a=0,b=dhx.Date.add(this.wb,-this.Ca,"day");b=dhx.Date.datePart(b);var c=0,d="";if(this.a.week_number){c=1;var e=dhx.Date.add(b,(this.Xb+1)%2,"day");d+='<table cellspacing="0" cellpadding="0" style="float: left;"><tbody>';for(var f=0;f<this.D;f++){var g=this.ea[f]-2,h=this.U[0]-2,i=this.z.calendar_week(e),j="dhx_cal_week_num";if(!this.a.skip_empty_weeks&&(f==this.D-1&&this.Wa>=7||
f==this.D-2&&this.Wa==14)){j="dhx_next_month";i=""}if(f==this.D-1){j+=" dhx_cal_day_num_bborder";g+=1}d+="<tr><td>";d+="<div class='"+j+"' style='width:"+h+"px; height:"+g+"px; line-height:"+g+"px;' >"+i+"</div>";d+="</td></tr>";e=dhx.Date.add(e,7,"day")}d+="</tbody></table>"}var l=dhx.Date.datePart(new Date);d+='<table cellspacing="0" cellpadding="0"><tbody>';var k=this.D*7-1;for(f=0;f<this.D;f++){d+="<tr>";for(i=0;i<7;i++){var n=this.z.calendar_day(b),m=this.z.calendar_date(b);j="dhx_cal_day_num";
if(a<this.Ca){j="dhx_prev_month";m=n=""}if(a>k-this.Wa){j="dhx_next_month";m=n=""}g=this.ea[f]-2;h=this.U[i+c]-2;if(i==6){j+=" dhx_cal_day_num_rborder";h+=1}if(f==this.D-1){j+=" dhx_cal_day_num_bborder";g+=1}d+="<td>";if(l.valueOf()==b.valueOf())j+=" dhx_cal_current_day";d+="<div class='"+j+"' style='width:"+h+"px; height:"+g+"px; line-height:"+g+"px;' date='"+m+"'>"+n+"</div>";d+="</td>";b=dhx.Date.add(b,1,"day");a++}d+="</tr>"}d+="</tbody></table>";return d},Zc:function(){var a="";a+="<select class='dhx_hour_select'>";
for(var b=this.a.hour_start,c=this.a.hour_end,d=dhx.Date.datePart(new Date),e=b;e<c;e++){d.setHours(e);a+="<option value='"+e+"'>"+dhx.Date.dateToStr(this.a.hour_format)(d)+"</option>"}a+="</select>";a+="<select class='dhx_minute_select'>";var f=0;for(d=f;d<60;d+=this.a.minute_step)a+="<option value='"+d+"'>"+dhx.math.toFixed(d)+"</option>";a+="</select>";return a},zc:function(){for(var a=["dhx_cal_prev_button","dhx_cal_next_button"],b="",c=0;c<2;c++){var d=a[c];b+="<div class='"+d+"' navigation='true'><div></div></div>"}return b},
on_click:{dhx_cal_next_button:function(){this.showCalendar(dhx.Date.add(this.a.date,1,"month"))},dhx_cal_prev_button:function(){this.showCalendar(dhx.Date.add(this.a.date,-1,"month"))},dhx_cal_day_num:function(a,b,c){a=c.getAttribute("date");var d=dhx.Date.strToDate(this.a.calendar_date_format);a=d(a);if(this.a.time_select){var e=this.Ma.lastChild,f=e.getElementsByTagName("select");a.setMinutes(f[0].value*60+f[1].value*1)}this.selectDate(dhx.Date.datePart(new Date(a)));this.callEvent("onDateSelected",
[a]);return a}}},dhx.MouseEvents,dhx.Settings,dhx.EventSystem,dhx.Movable,dhx.ui.map.view);
