package com.microwill.prfrmn.BGM.entity;

// Generated 2013-12-1 10:27:15 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPatient generated by hbm2java
 */
@Entity
@Table(name = "t_patient", catalog = "BGM")
public class TPatient implements java.io.Serializable {

	private String patientId;
	private String recordNo;
	private String idNo;
	private String insuranceId;
	private String name;
	private Integer sex;
	private Integer age;
	private Date bornDate;
	private String contact1;
	private String contact2;
	private String address;
	private Integer type;
	private Date checkinTime;
	private Date checkoutTime;
	private String memo;

	public TPatient() {
	}

	public TPatient(String patientId, Date bornDate, Date checkinTime,
			Date checkoutTime) {
		this.patientId = patientId;
		this.bornDate = bornDate;
		this.checkinTime = checkinTime;
		this.checkoutTime = checkoutTime;
	}

	public TPatient(String patientId, String recordNo, String idNo,
			String insuranceId, String name, Integer sex, Integer age,
			Date bornDate, String contact1, String contact2, String address,
			Integer type, Date checkinTime, Date checkoutTime, String memo) {
		this.patientId = patientId;
		this.recordNo = recordNo;
		this.idNo = idNo;
		this.insuranceId = insuranceId;
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.bornDate = bornDate;
		this.contact1 = contact1;
		this.contact2 = contact2;
		this.address = address;
		this.type = type;
		this.checkinTime = checkinTime;
		this.checkoutTime = checkoutTime;
		this.memo = memo;
	}

	@Id
	@Column(name = "patient_id", unique = true, nullable = false, length = 32)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "record_no", length = 32)
	public String getRecordNo() {
		return this.recordNo;
	}

	public void setRecordNo(String recordNo) {
		this.recordNo = recordNo;
	}

	@Column(name = "id_no", length = 16)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "insurance_id", length = 16)
	public String getInsuranceId() {
		return this.insuranceId;
	}

	public void setInsuranceId(String insuranceId) {
		this.insuranceId = insuranceId;
	}

	@Column(name = "name", length = 12)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "born_date", nullable = false, length = 19)
	public Date getBornDate() {
		return this.bornDate;
	}

	public void setBornDate(Date bornDate) {
		this.bornDate = bornDate;
	}

	@Column(name = "contact1", length = 30)
	public String getContact1() {
		return this.contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	@Column(name = "contact2", length = 30)
	public String getContact2() {
		return this.contact2;
	}

	public void setContact2(String contact2) {
		this.contact2 = contact2;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checkin_time", nullable = false, length = 19)
	public Date getCheckinTime() {
		return this.checkinTime;
	}

	public void setCheckinTime(Date checkinTime) {
		this.checkinTime = checkinTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checkout_time", nullable = false, length = 19)
	public Date getCheckoutTime() {
		return this.checkoutTime;
	}

	public void setCheckoutTime(Date checkoutTime) {
		this.checkoutTime = checkoutTime;
	}

	@Column(name = "memo", length = 150)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
