package com.microwill.prfrmn.BGM.entity;

// Generated 2013-12-1 10:27:15 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPlan generated by hbm2java
 */
@Entity
@Table(name = "t_plan", catalog = "BGM")
public class TPlan implements java.io.Serializable {

	private String planId;
	private String patientId;
	private String userId;
	private Date beginTime;
	private Date endTime;
	private String memo;
	private Integer dectectTime;

	public TPlan() {
	}

	public TPlan(String planId, Date beginTime, Date endTime) {
		this.planId = planId;
		this.beginTime = beginTime;
		this.endTime = endTime;
	}

	public TPlan(String planId, String patientId, String userId,
			Date beginTime, Date endTime, String memo, Integer dectectTime) {
		this.planId = planId;
		this.patientId = patientId;
		this.userId = userId;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.memo = memo;
		this.dectectTime = dectectTime;
	}

	@Id
	@Column(name = "plan_id", unique = true, nullable = false, length = 32)
	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	@Column(name = "patient_id", length = 32)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "begin_time", nullable = false, length = 19)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", nullable = false, length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "memo", length = 150)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "dectect_time")
	public Integer getDectectTime() {
		return this.dectectTime;
	}

	public void setDectectTime(Integer dectectTime) {
		this.dectectTime = dectectTime;
	}

}
