package com.microwill.prfrmn.BGM.entity;

// Generated 2013-12-14 14:53:46 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TResult generated by hbm2java
 */
@Entity
@Table(name = "t_result", catalog = "BGM")
public class TResult implements java.io.Serializable {

	private String checkId;
	private String patientId;
	private String userId;
	private String machId;
	private String checkResult;
	private String analysisResult;
	private String checkTime;
	private String memo;

	public TResult() {
	}

	public TResult(String checkId) {
		this.checkId = checkId;
	}

	public TResult(String checkId, String patientId, String userId,
			String machId, String checkResult, String analysisResult,
			String checkTime, String memo) {
		this.checkId = checkId;
		this.patientId = patientId;
		this.userId = userId;
		this.machId = machId;
		this.checkResult = checkResult;
		this.analysisResult = analysisResult;
		this.checkTime = checkTime;
		this.memo = memo;
	}

	@Id
	@Column(name = "check_id", unique = true, nullable = false, length = 32)
	public String getCheckId() {
		return this.checkId;
	}

	public void setCheckId(String checkId) {
		this.checkId = checkId;
	}

	@Column(name = "patient_id", length = 32)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "mach_id", length = 32)
	public String getMachId() {
		return this.machId;
	}

	public void setMachId(String machId) {
		this.machId = machId;
	}

	@Column(name = "check_result", length = 50)
	public String getCheckResult() {
		return this.checkResult;
	}

	public void setCheckResult(String checkResult) {
		this.checkResult = checkResult;
	}

	@Column(name = "analysis_result", length = 100)
	public String getAnalysisResult() {
		return this.analysisResult;
	}

	public void setAnalysisResult(String analysisResult) {
		this.analysisResult = analysisResult;
	}

	@Column(name = "check_time", length = 10)
	public String getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	@Column(name = "memo", length = 100)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
